"""
data_venues.py
==============
Die 16 offiziellen Spielorte der FIFA WM 2026.
"""

from __future__ import annotations

VENUES: list[dict] = [
    # ── USA (11) ──────────────────────────────────────────────
    {
        "id": "metlife",
        "name": "MetLife Stadium",
        "city": "NY-New Jersey",
        "state": "New Jersey",
        "country": "USA",
        "flag": "us",
        "capacity": 82_500,
        "note": "Finale",
        "highlight": True,
        "lat": 40.8135, "lon": -74.0745,
    },
    {
        "id": "att",
        "name": "AT&T Stadium",
        "city": "Arlington",
        "state": "Texas",
        "country": "USA",
        "flag": "us",
        "capacity": 80_000,
        "note": "",
        "highlight": False,
        "lat": 32.7480, "lon": -97.0928,
    },
    {
        "id": "rosebowl",
        "name": "Rose Bowl",
        "city": "Pasadena",
        "state": "Kalifornien",
        "country": "USA",
        "flag": "us",
        "capacity": 92_542,
        "note": "Größtes WM-Stadion",
        "highlight": False,
        "lat": 34.1614, "lon": -118.1676,
    },
    {
        "id": "sofi",
        "name": "SoFi Stadium",
        "city": "Inglewood / Los Angeles",
        "state": "Kalifornien",
        "country": "USA",
        "flag": "us",
        "capacity": 70_240,
        "note": "",
        "highlight": False,
        "lat": 33.9535, "lon": -118.3392,
    },
    {
        "id": "levis",
        "name": "Levi's Stadium",
        "city": "Santa Clara / San Francisco",
        "state": "Kalifornien",
        "country": "USA",
        "flag": "us",
        "capacity": 68_500,
        "note": "",
        "highlight": False,
        "lat": 37.4033, "lon": -121.9694,
    },
    {
        "id": "lumen",
        "name": "Lumen Field",
        "city": "Seattle",
        "state": "Washington",
        "country": "USA",
        "flag": "us",
        "capacity": 69_000,
        "note": "",
        "highlight": False,
        "lat": 47.5952, "lon": -122.3316,
    },
    {
        "id": "arrowhead",
        "name": "Arrowhead Stadium",
        "city": "Kansas City",
        "state": "Missouri",
        "country": "USA",
        "flag": "us",
        "capacity": 76_416,
        "note": "",
        "highlight": False,
        "lat": 39.0489, "lon": -94.4839,
    },
    {
        "id": "nrg",
        "name": "NRG Stadium",
        "city": "Houston",
        "state": "Texas",
        "country": "USA",
        "flag": "us",
        "capacity": 72_220,
        "note": "",
        "highlight": False,
        "lat": 29.6847, "lon": -95.4107,
    },
    {
        "id": "hardrock",
        "name": "Hard Rock Stadium",
        "city": "Miami Gardens / Miami",
        "state": "Florida",
        "country": "USA",
        "flag": "us",
        "capacity": 65_326,
        "note": "",
        "highlight": False,
        "lat": 25.9580, "lon": -80.2389,
    },
    {
        "id": "lincoln",
        "name": "Lincoln Financial Field",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "country": "USA",
        "flag": "us",
        "capacity": 69_328,
        "note": "",
        "highlight": False,
        "lat": 39.9008, "lon": -75.1675,
    },
    {
        "id": "gillette",
        "name": "Gillette Stadium",
        "city": "Foxborough / Boston",
        "state": "Massachusetts",
        "country": "USA",
        "flag": "us",
        "capacity": 65_878,
        "note": "",
        "highlight": False,
        "lat": 42.0909, "lon": -71.2643,
    },

    # ── Mexiko (3) ────────────────────────────────────────────
    {
        "id": "azteca",
        "name": "Estadio Azteca",
        "city": "Mexiko-Stadt",
        "state": "",
        "country": "Mexiko",
        "flag": "mx",
        "capacity": 87_523,
        "note": "Eröffnungsspiel",
        "highlight": True,
        "lat": 19.3029, "lon": -99.1505,
    },
    {
        "id": "bbva",
        "name": "Estadio BBVA",
        "city": "Monterrey",
        "state": "Nuevo León",
        "country": "Mexiko",
        "flag": "mx",
        "capacity": 51_350,
        "note": "",
        "highlight": False,
        "lat": 25.6693, "lon": -100.3098,
    },
    {
        "id": "akron",
        "name": "Estadio Akron",
        "city": "Guadalajara",
        "state": "Jalisco",
        "country": "Mexiko",
        "flag": "mx",
        "capacity": 49_850,
        "note": "",
        "highlight": False,
        "lat": 20.6673, "lon": -103.4018,
    },

    # ── Kanada (2) ────────────────────────────────────────────
    {
        "id": "bcplace",
        "name": "BC Place",
        "city": "Vancouver",
        "state": "British Columbia",
        "country": "Kanada",
        "flag": "ca",
        "capacity": 54_500,
        "note": "",
        "highlight": False,
        "lat": 49.2767, "lon": -123.1116,
    },
    {
        "id": "bmo",
        "name": "BMO Field",
        "city": "Toronto",
        "state": "Ontario",
        "country": "Kanada",
        "flag": "ca",
        "capacity": 45_000,
        "note": "",
        "highlight": False,
        "lat": 43.6333, "lon": -79.4189,
    },
]


def by_country() -> dict[str, list[dict]]:
    """Gruppiert Spielorte nach Land."""
    result: dict[str, list[dict]] = {}
    for v in VENUES:
        result.setdefault(v["country"], []).append(v)
    return result
