"""
data_squads.py  –  Offizielle WM-2026-Kader (FIFA Squad List, 5. Juni 2026)
Positionen: TW · IV · ZM · ST  (GK→TW, DF→IV, MF→ZM, FW→ST)
"""
from __future__ import annotations
import re

def _c(club: str) -> str:
    return re.sub(r"\s*\([A-Z]{2,3}\)$", "", club).strip()

def _p(pos: str) -> str:
    return {"GK": "TW", "DF": "IV", "MF": "ZM", "FW": "ST"}.get(pos, pos)

def _squad(rows):
    return [{"name": n, "pos": _p(p), "club": _c(c)} for n, p, c in rows]

SQUADS: dict[str, list[dict]] = {

"dz": _squad([  # Algerien
    ("Melvin Mastil","GK","FC Stade Nyonnais (SUI)"),
    ("Aissa Mandi","DF","Lille OSC (FRA)"),
    ("Achraf Abada","DF","USM Alger (ALG)"),
    ("Mohamed Amine Tougai","DF","Espérance De Tunisie (TUN)"),
    ("Zineddine Belaid","DF","JS Kabylie (ALG)"),
    ("Ramiz Zerrouki","MF","FC Twente (NED)"),
    ("Riyad Mahrez","FW","Al Ahli FC (KSA)"),
    ("Houssem Aouar","MF","Al Ittihad (KSA)"),
    ("Amine Gouiri","FW","Olympique Marseille (FRA)"),
    ("Fares Chaibi","MF","Eintracht Frankfurt (GER)"),
    ("Anis Hadj Moussa","FW","Feyenoord Rotterdam (NED)"),
    ("Nadhir Benbouali","FW","Györi ETO FC (HUN)"),
    ("Jaouen Hadjam","DF","BSC Young Boys (SUI)"),
    ("Hicham Boudaoui","MF","OGC Nice (FRA)"),
    ("Rayan Ait-Nouri","DF","Manchester City FC (ENG)"),
    ("Oussama Benbot","GK","USM Alger (ALG)"),
    ("Rak Belghali","DF","Hellas Verona FC (ITA)"),
    ("Mohammed Amoura","FW","VfL Wolfsburg (GER)"),
    ("Nabil Bentaleb","MF","Lille OSC (FRA)"),
    ("Adil Boulbina","FW","Al Duhail SC (QAT)"),
    ("Ramy Bensebaini","DF","Borussia Dortmund (GER)"),
    ("Ibrahim Maza","MF","Bayer Leverkusen (GER)"),
    ("Luca Zidane","GK","Granada CF (ESP)"),
    ("Yassine Titraoui","MF","Sporting Charleroi (BEL)"),
    ("Fares Ghedjemis","FW","Frosinone (ITA)"),
    ("Samir Chergui","DF","Paris FC (FRA)"),
]),

"ar": _squad([  # Argentinien
    ("Juan Musso","GK","Atlético De Madrid (ESP)"),
    ("Leonardo Balerdi","DF","Olympique Marseille (FRA)"),
    ("Nicolas Tagliafico","DF","Olympique Lyonnais (FRA)"),
    ("Gonzalo Montiel","DF","CA River Plate (ARG)"),
    ("Leandro Paredes","MF","CA Boca Juniors (ARG)"),
    ("Lisandro Martinez","DF","Manchester United FC (ENG)"),
    ("Rodrigo De Paul","MF","Inter Miami CF (USA)"),
    ("Valentin Barco","MF","RC Strasbourg (FRA)"),
    ("Julian Alvarez","FW","Atlético De Madrid (ESP)"),
    ("Lionel Messi","FW","Inter Miami CF (USA)"),
    ("Giovani Lo Celso","MF","Real Betis (ESP)"),
    ("Geronimo Rulli","GK","Olympique Marseille (FRA)"),
    ("Cristian Romero","DF","Tottenham Hotspur FC (ENG)"),
    ("Exequiel Palacios","MF","Bayer Leverkusen (GER)"),
    ("Nico Gonzalez","MF","Atlético De Madrid (ESP)"),
    ("Thiago Almada","FW","Atlético De Madrid (ESP)"),
    ("Giuliano Simeone","FW","Atlético De Madrid (ESP)"),
    ("Nico Paz","FW","Como (ITA)"),
    ("Nicolas Otamendi","DF","SL Benfica (POR)"),
    ("Alexis Mac Allister","MF","Liverpool FC (ENG)"),
    ("Jose Manuel Lopez","FW","SE Palmeiras (BRA)"),
    ("Lautaro Martinez","FW","FC Internazionale Milano (ITA)"),
    ("Emiliano Martinez","GK","Aston Villa FC (ENG)"),
    ("Enzo Fernandez","MF","Chelsea FC (ENG)"),
    ("Facundo Medina","DF","Olympique Marseille (FRA)"),
    ("Nahuel Molina","DF","Atlético De Madrid (ESP)"),
]),

"au": _squad([  # Australien
    ("Mathew Ryan","GK","Levante UD (ESP)"),
    ("Milos Degenek","DF","APOEL FC (CYP)"),
    ("Alessandro Circati","DF","Parma (ITA)"),
    ("Jacob Italiano","DF","Grazer AK (AUT)"),
    ("Jordan Bos","DF","Feyenoord Rotterdam (NED)"),
    ("Jason Geria","DF","Albirex Niigata (JPN)"),
    ("Mathew Leckie","FW","Melbourne City FC (AUS)"),
    ("Connor Metcalfe","MF","FC St. Pauli (GER)"),
    ("Mohamed Toure","FW","Norwich City FC (ENG)"),
    ("Ajdin Hrustic","FW","SC Heracles Almelo (NED)"),
    ("Awer Mabil","FW","CD Castellón (ESP)"),
    ("Paul Izzo","GK","Randers FC (DEN)"),
    ("Aiden O'Neill","MF","New York City FC (USA)"),
    ("Cameron Devlin","MF","Heart Of Midlothian FC (SCO)"),
    ("Kai Trewin","DF","New York City FC (USA)"),
    ("Aziz Behich","DF","Melbourne City FC (AUS)"),
    ("Nestory Irankunda","FW","Watford FC (ENG)"),
    ("Patrick Beach","GK","Melbourne City FC (AUS)"),
    ("Harry Souttar","DF","Leicester City FC (ENG)"),
    ("Cristian Volpato","FW","US Sassuolo (ITA)"),
    ("Cameron Burgess","DF","Swansea City AFC (WAL)"),
    ("Jackson Irvine","MF","FC St. Pauli (GER)"),
    ("Nishan Velupillay","FW","Melbourne Victory FC (AUS)"),
    ("Paul Okon-Engstler","MF","Sydney FC (AUS)"),
    ("Lucas Herrington","DF","Colorado Rapids (USA)"),
    ("Tete Yengi","FW","FC Machida Zelvia (JPN)"),
]),

"at": _squad([  # Österreich
    ("Alexander Schlager","GK","FC Red Bull Salzburg (AUT)"),
    ("David Affengruber","DF","Elche CF (ESP)"),
    ("Kevin Danso","DF","Tottenham Hotspur FC (ENG)"),
    ("Xaver Schlager","MF","RB Leipzig (GER)"),
    ("Stefan Posch","DF","1. FSV Mainz 05 (GER)"),
    ("Nicolas Seiwald","MF","RB Leipzig (GER)"),
    ("Marko Arnautovic","FW","FK Crvena Zvezda (SRB)"),
    ("David Alaba","DF","Real Madrid C. F. (ESP)"),
    ("Marcel Sabitzer","MF","Borussia Dortmund (GER)"),
    ("Florian Grillitsch","MF","SC Braga (POR)"),
    ("Michael Gregoritsch","FW","FC Augsburg (GER)"),
    ("Florian Wiegele","GK","FC Viktoria Plzeň (CZE)"),
    ("Patrick Pentz","GK","Brøndby IF (DEN)"),
    ("Sasa Kalajdzic","FW","LASK Linz (AUT)"),
    ("Philipp Lienhart","DF","SC Freiburg (GER)"),
    ("Phillip Mwene","DF","1. FSV Mainz 05 (GER)"),
    ("Carney Chukwuemeka","MF","Borussia Dortmund (GER)"),
    ("Romano Schmid","MF","SV Werder Bremen (GER)"),
    ("Christoph Baumgartner","MF","RB Leipzig (GER)"),
    ("Konrad Laimer","MF","FC Bayern München (GER)"),
    ("Patrick Wimmer","FW","VfL Wolfsburg (GER)"),
    ("Alexander Prass","MF","TSG Hoffenheim (GER)"),
    ("Marco Friedl","DF","SV Werder Bremen (GER)"),
    ("Paul Wanner","MF","PSV Eindhoven (NED)"),
    ("Michael Svoboda","DF","Venezia FC (ITA)"),
    ("Alessandro Schoepf","MF","Wolfsberger AC (AUT)"),
]),

"be": _squad([  # Belgien
    ("Thibaut Courtois","GK","Real Madrid C. F. (ESP)"),
    ("Zeno Debast","DF","Sporting CP (POR)"),
    ("Arthur Theate","DF","Eintracht Frankfurt (GER)"),
    ("Brandon Mechele","DF","Club Brugge (BEL)"),
    ("Maxim De Cuyper","DF","Brighton & Hove Albion FC (ENG)"),
    ("Axel Witsel","MF","Girona FC (ESP)"),
    ("Kevin De Bruyne","MF","SSC Napoli (ITA)"),
    ("Youri Tielemans","MF","Aston Villa FC (ENG)"),
    ("Romelu Lukaku","FW","SSC Napoli (ITA)"),
    ("Leandro Trossard","FW","Arsenal FC (ENG)"),
    ("Jeremy Doku","FW","Manchester City FC (ENG)"),
    ("Senne Lammens","GK","Manchester United FC (ENG)"),
    ("Mike Penders","GK","RC Strasbourg (FRA)"),
    ("Dodi Lukebakio","FW","SL Benfica (POR)"),
    ("Thomas Meunier","DF","Lille OSC (FRA)"),
    ("Koni De Winter","DF","AC Milan (ITA)"),
    ("Charles De Ketelaere","FW","Atalanta Bergamo (ITA)"),
    ("Joaquin Seys","DF","Club Brugge (BEL)"),
    ("Diego Moreira","MF","RC Strasbourg (FRA)"),
    ("Hans Vanaken","MF","Club Brugge (BEL)"),
    ("Timothy Castagne","DF","Fulham FC (ENG)"),
    ("Alexis Saelemaekers","MF","AC Milan (ITA)"),
    ("Nicolas Raskin","MF","Rangers FC (SCO)"),
    ("Amadou Onana","MF","Aston Villa FC (ENG)"),
    ("Nathan Ngoy","DF","Lille OSC (FRA)"),
    ("Matias Fernandez-Pardo","FW","Lille OSC (FRA)"),
]),

"ba": _squad([  # Bosnien und Herzegowina
    ("Nikola Vasilj","GK","FC St. Pauli (GER)"),
    ("Nihad Mujakic","DF","Gaziantep FK (TUR)"),
    ("Dennis Hadzikadunic","DF","UC Sampdoria (ITA)"),
    ("Tarik Muharemovic","DF","US Sassuolo (ITA)"),
    ("Sead Kolasinac","DF","Atalanta Bergamo (ITA)"),
    ("Benjamin Tahirovic","MF","Brøndby IF (DEN)"),
    ("Amar Dedic","DF","SL Benfica (POR)"),
    ("Armin Gigovic","MF","BSC Young Boys (SUI)"),
    ("Samed Bazdar","FW","Jagiellonia Białystok (POL)"),
    ("Ermedin Demirovic","FW","VfB Stuttgart (GER)"),
    ("Edin Dzeko","FW","FC Schalke 04 (GER)"),
    ("Mladen Jurkas","GK","FK Borac Banja Luka (BIH)"),
    ("Ivan Basic","MF","FC Astana (KAZ)"),
    ("Ivan Sunjic","MF","Pafos FC (CYP)"),
    ("Amar Memic","MF","FC Viktoria Plzeň (CZE)"),
    ("Amir Hadziahmetovic","MF","Hull City FC (ENG)"),
    ("Dzenis Burnic","MF","Karlsruher SC (GER)"),
    ("Nikola Katic","DF","FC Schalke 04 (GER)"),
    ("Kerim Alajbegovic","FW","FC Red Bull Salzburg (AUT)"),
    ("Esmir Bajraktarevic","FW","PSV Eindhoven (NED)"),
    ("Stjepan Radeljic","DF","HNK Rijeka (CRO)"),
    ("Martin Zlomislic","GK","HNK Rijeka (CRO)"),
    ("Haris Tabakovic","FW","Borussia Mönchengladbach (GER)"),
    ("Nidal Celik","DF","RC Lens (FRA)"),
    ("Jovo Lukic","FW","Universitatea Cluj (ROU)"),
    ("Ermin Mahmic","MF","FC Slovan Liberec (CZE)"),
]),

"br": _squad([  # Brasilien
    ("Alisson Becker","GK","Liverpool FC (ENG)"),
    ("Wesley","DF","AS Roma (ITA)"),
    ("Gabriel Magalhaes","DF","Arsenal FC (ENG)"),
    ("Marquinhos","DF","Paris Saint-Germain (FRA)"),
    ("Casemiro","MF","Manchester United FC (ENG)"),
    ("Alex Sandro","DF","CR Flamengo (BRA)"),
    ("Vinicius Junior","FW","Real Madrid C. F. (ESP)"),
    ("Bruno Guimaraes","MF","Newcastle United FC (ENG)"),
    ("Matheus Cunha","FW","Manchester United FC (ENG)"),
    ("Neymar Jr.","FW","Santos FC (BRA)"),
    ("Raphinha","FW","FC Barcelona (ESP)"),
    ("Weverton","GK","Grêmio FBPA (BRA)"),
    ("Danilo","DF","CR Flamengo (BRA)"),
    ("Bremer","DF","Juventus FC (ITA)"),
    ("Leo Pereira","DF","CR Flamengo (BRA)"),
    ("Douglas Santos","DF","FC Zenit St. Petersburg (RUS)"),
    ("Fabinho","MF","Al Ittihad (KSA)"),
    ("Danilo Santos","MF","Botafogo (BRA)"),
    ("Endrick","FW","Olympique Lyonnais (FRA)"),
    ("Lucas Paqueta","MF","CR Flamengo (BRA)"),
    ("Luiz Henrique","FW","FC Zenit St. Petersburg (RUS)"),
    ("Gabriel Martinelli","FW","Arsenal FC (ENG)"),
    ("Ederson","GK","Fenerbahçe SK (TUR)"),
    ("Roger Ibanez","DF","Al Ahli FC (KSA)"),
    ("Igor Thiago","FW","Brentford FC (ENG)"),
    ("Rayan","FW","AFC Bournemouth (ENG)"),
]),

"cv": _squad([  # Kap Verde
    ("Vozinha","GK","GD Chaves (POR)"),
    ("Stopira","DF","SCU Torreense (POR)"),
    ("Diney Borges","DF","Al Bataeh Club (UAE)"),
    ("Pico Lopes","DF","Shamrock Rovers FC (IRL)"),
    ("Logan Costa","DF","Villarreal CF (ESP)"),
    ("Kevin Pina","MF","FC Krasnodar (RUS)"),
    ("Jovane Cabral","MF","CF Estrela Da Amadora (POR)"),
    ("Joao Paulo","MF","FC FCSB (ROU)"),
    ("Gilson Benchimol","FW","FC Akron Tolyatti (RUS)"),
    ("Jamiro Monteiro","MF","PEC Zwolle (NED)"),
    ("Garry Rodrigues","MF","Apollon Limassol (CYP)"),
    ("Marcio Rosa","GK","PFC Montana (BUL)"),
    ("Sidny Lopes Cabral","DF","SL Benfica (POR)"),
    ("Deroy Duarte","MF","PFC Ludogorets Razgrad (BUL)"),
    ("Laros Duarte","MF","Puskás Akadémia FC (HUN)"),
    ("Yannick Semedo","MF","SC Farense (POR)"),
    ("Willy Semedo","MF","AC Omonia (CYP)"),
    ("Telmo Arcanjo","MF","Vitória SC (POR)"),
    ("Dailon Livramento","FW","Casa Pia AC (POR)"),
    ("Ryan Mendes","FW","Iğdır FK (TUR)"),
    ("Nuno Da Costa","MF","Başakşehir FK (TUR)"),
    ("Steven Moreira","DF","Columbus Crew (USA)"),
    ("CJ Dos Santos","GK","San Diego FC (USA)"),
    ("Wagner Pina","DF","Trabzonspor (TUR)"),
    ("Kelvin Pires","DF","SJK (FIN)"),
    ("Helio Varela","MF","Maccabi Tel-Aviv FC (ISR)"),
]),

"ca": _squad([  # Kanada
    ("Dayne St. Clair","GK","Inter Miami CF (USA)"),
    ("Alistair Johnston","DF","Celtic FC (SCO)"),
    ("Ale Jones","DF","Middlesbrough FC (ENG)"),
    ("Luc De Fougerolles","DF","FCV Dender EH (BEL)"),
    ("Joel Waterman","DF","Chicago Fire FC (USA)"),
    ("Mathieu Choiniere","MF","LAFC (USA)"),
    ("Stephen Eustaquio","MF","LAFC (USA)"),
    ("Ismael Kone","MF","US Sassuolo (ITA)"),
    ("Cyle Larin","FW","Southampton FC (ENG)"),
    ("Jonathan David","FW","Juventus FC (ITA)"),
    ("Liam Millar","MF","Hull City FC (ENG)"),
    ("Tani Oluwaseyi","FW","Villarreal CF (ESP)"),
    ("Derek Cornelius","DF","Rangers FC (SCO)"),
    ("Jacob Shaffelburg","MF","LAFC (USA)"),
    ("Moise Bombito","DF","OGC Nice (FRA)"),
    ("Maxime Crepeau","GK","Orlando City SC (USA)"),
    ("Tajon Buchanan","FW","Villarreal CF (ESP)"),
    ("Owen Goodman","GK","Barnsley (ENG)"),
    ("Alphonso Davies","DF","FC Bayern München (GER)"),
    ("Ali Ahmed","FW","Norwich City FC (ENG)"),
    ("Jonathan Osorio","MF","Toronto FC (CAN)"),
    ("Richie Laryea","DF","Toronto FC (CAN)"),
    ("Niko Sigur","DF","HNK Hajduk Split (CRO)"),
    ("Promise David","FW","Royale Union Saint-Gilloise (BEL)"),
    ("Nathan Saliba","MF","RSC Anderlecht (BEL)"),
    ("Marcelo Flores","MF","Tigres UANL (MEX)"),
]),

"co": _squad([  # Kolumbien
    ("David Ospina","GK","Atlético Nacional (COL)"),
    ("Daniel Munoz","DF","Crystal Palace FC (ENG)"),
    ("Jhon Lucumi","DF","Bologna FC (ITA)"),
    ("Santiago Arias","DF","CA Independiente (ARG)"),
    ("Kevin Castano","MF","CA River Plate (ARG)"),
    ("Richard Rios","MF","SL Benfica (POR)"),
    ("Luis Diaz","FW","FC Bayern München (GER)"),
    ("Jorge Carrascal","MF","CR Flamengo (BRA)"),
    ("Jhon Cordoba","FW","FC Krasnodar (RUS)"),
    ("James Rodriguez","MF","Minnesota United FC (USA)"),
    ("Jhon Arias","MF","SE Palmeiras (BRA)"),
    ("Camilo Vargas","GK","Atlas FC (MEX)"),
    ("Yerry Mina","DF","Cagliari (ITA)"),
    ("Gustavo Puerta","DF","Racing Santander (ESP)"),
    ("Juan Portilla","MF","Athletico Paranaense (BRA)"),
    ("Jefferson Lerma","MF","Crystal Palace FC (ENG)"),
    ("Johan Mojica","DF","RCD Mallorca (ESP)"),
    ("Willer Ditta","DF","CF Cruz Azul (MEX)"),
    ("Cucho Hernandez","FW","Real Betis (ESP)"),
    ("Juan Quintero","MF","CA River Plate (ARG)"),
    ("Jaminton Campaz","FW","CA Rosario Central (ARG)"),
    ("Deiver Machado","DF","FC Nantes (FRA)"),
    ("Davinson Sanchez","DF","Galatasaray SK (TUR)"),
    ("Alvaro Montero","GK","CA Vélez Sarsfield (ARG)"),
    ("Luis Suarez","FW","Sporting CP (POR)"),
    ("Andres Gomez","FW","CR Vasco Da Gama (BRA)"),
]),

"cd": _squad([  # DR Kongo
    ("Lionel Mpasi","GK","Le Havre AC (FRA)"),
    ("Aaron Wan-Bissaka","DF","West Ham United FC (ENG)"),
    ("Steve Kapuadi","DF","Widzew Łódź (POL)"),
    ("Axel Tuanzebe","DF","Burnley FC (ENG)"),
    ("Dylan Batubinsika","DF","AEL FC (GRE)"),
    ("Ngalayel Mukau","MF","Lille OSC (FRA)"),
    ("Nathanael Mbuku","MF","Montpellier HSC (FRA)"),
    ("Samuel Moutoussamy","MF","Atromitos FC (GRE)"),
    ("Brian Cipenga","FW","CD Castellón (ESP)"),
    ("Theo Bongonda","MF","FC Spartak Moscow (RUS)"),
    ("Gael Kakuta","FW","AEL FC (GRE)"),
    ("Joris Kayembe","DF","KRC Genk (BEL)"),
    ("Meschack Elia","FW","Alanyaspor (TUR)"),
    ("Noah Sadiki","MF","Sunderland AFC (ENG)"),
    ("Aaron Tshibola","MF","Kilmarnock FC (SCO)"),
    ("Timothy Fayulu","GK","FC Noah (ARM)"),
    ("Cedric Bakambu","FW","Real Betis (ESP)"),
    ("Charles Pickel","MF","RCD Espanyol (ESP)"),
    ("Fiston Mayele","FW","Pyramids FC (EGY)"),
    ("Yoane Wissa","FW","Newcastle United FC (ENG)"),
    ("Matthieu Epolo","GK","Standard Liège (BEL)"),
    ("Chancel Mbemba","DF","Lille OSC (FRA)"),
    ("Simon Banza","FW","Al Jazira (UAE)"),
    ("Gedeon Kalulu","DF","Aris Limassol FC (CYP)"),
    ("Edo Kayembe","MF","Watford FC (ENG)"),
    ("Arthur Masuaku","DF","RC Lens (FRA)"),
]),

"ci": _squad([  # Elfenbeinküste
    ("Yahia Fofana","GK","Çaykur Rizespor (TUR)"),
    ("Ousmane Diomande","DF","Sporting CP (POR)"),
    ("Ghislain Konan","DF","Gil Vicente FC (POR)"),
    ("Jean Michael Seri","MF","NK Maribor (SVN)"),
    ("Wilfried Singo","DF","Galatasaray SK (TUR)"),
    ("Seko Fofana","MF","FC Porto (POR)"),
    ("Odilon Kossounou","DF","Atalanta Bergamo (ITA)"),
    ("Franck Kessie","MF","Al Ahli FC (KSA)"),
    ("Ange-Yoan Bonny","FW","FC Internazionale Milano (ITA)"),
    ("Simon Adingra","FW","AS Monaco (FRA)"),
    ("Yan Diomande","FW","RB Leipzig (GER)"),
    ("Elye Wahi","FW","OGC Nice (FRA)"),
    ("Christopher Operi","DF","Başakşehir FK (TUR)"),
    ("Oumar Diakite","FW","Cercle Brugge (BEL)"),
    ("Amad Diallo","FW","Manchester United FC (ENG)"),
    ("Mohamed Kone","GK","Sporting Charleroi (BEL)"),
    ("Guela Doue","DF","RC Strasbourg (FRA)"),
    ("Ibrahim Sangare","MF","Nottingham Forest FC (ENG)"),
    ("Nicolas Pepe","FW","Villarreal CF (ESP)"),
    ("Emmanuel Agbadou","DF","Beşiktaş JK (TUR)"),
    ("Evan Ndicka","DF","AS Roma (ITA)"),
    ("Evann Guessand","FW","Crystal Palace FC (ENG)"),
    ("Alban Lafont","GK","Panathinaikos FC (GRE)"),
    ("Bazoumana Toure","FW","TSG Hoffenheim (GER)"),
    ("Parfait Guiagon","MF","Sporting Charleroi (BEL)"),
    ("Christ Oulai","MF","Trabzonspor (TUR)"),
]),

"hr": _squad([  # Kroatien
    ("Dominik Livakovic","GK","GNK Dinamo Zagreb (CRO)"),
    ("Josip Stanisic","DF","FC Bayern München (GER)"),
    ("Marin Pongracic","DF","ACF Fiorentina (ITA)"),
    ("Josko Gvardiol","DF","Manchester City FC (ENG)"),
    ("Duje Caleta-Car","DF","Real Sociedad (ESP)"),
    ("Josip Sutalo","DF","AFC Ajax (NED)"),
    ("Nikola Moro","MF","Bologna FC (ITA)"),
    ("Mateo Kovacic","MF","Manchester City FC (ENG)"),
    ("Andrej Kramaric","FW","TSG Hoffenheim (GER)"),
    ("Luka Modric","MF","AC Milan (ITA)"),
    ("Ante Budimir","FW","CA Osasuna (ESP)"),
    ("Ivor Pandur","GK","Hull City FC (ENG)"),
    ("Nikola Vlasic","MF","Torino FC (ITA)"),
    ("Ivan Perisic","FW","PSV Eindhoven (NED)"),
    ("Mario Pasalic","MF","Atalanta Bergamo (ITA)"),
    ("Martin Baturina","MF","Como (ITA)"),
    ("Petar Sucic","MF","FC Internazionale Milano (ITA)"),
    ("Kristijan Jakic","DF","FC Augsburg (GER)"),
    ("Toni Fruk","MF","HNK Rijeka (CRO)"),
    ("Igor Matanovic","FW","SC Freiburg (GER)"),
    ("Luka Sucic","MF","Real Sociedad (ESP)"),
    ("Luka Vuskovic","DF","Hamburger SV (GER)"),
    ("Dominik Kotarski","GK","FC København (DEN)"),
    ("Marco Pasalic","FW","Orlando City SC (USA)"),
    ("Martin Erlic","DF","FC Midtjylland (DEN)"),
    ("Petar Musa","FW","FC Dallas (USA)"),
]),

"cw": _squad([  # Curaçao
    ("Eloy Room","GK","Miami FC (USA)"),
    ("Shurandy Sambo","DF","Sparta Rotterdam (NED)"),
    ("Jurien Gaari","DF","Abha Club (KSA)"),
    ("Roshon Van Eijma","DF","RKC Waalwijk (NED)"),
    ("Sherel Floranus","DF","PEC Zwolle (NED)"),
    ("Godfried Roemeratoe","MF","RKC Waalwijk (NED)"),
    ("Juninho Bacuna","MF","FC Volendam (NED)"),
    ("Livano Comenencia","MF","FC Zürich (SUI)"),
    ("Juergen Locadia","FW","Miami FC (USA)"),
    ("Leandro Bacuna","MF","Iğdır FK (TUR)"),
    ("Jeremy Antonisse","FW","AE Kifisia FC (GRE)"),
    ("Sontje Hansen","FW","Middlesbrough FC (ENG)"),
    ("Tyrese Noslin","FW","SC Telstar (NED)"),
    ("Kenji Gorre","MF","Maccabi Haifa FC (ISR)"),
    ("Arjany Martha","MF","Rotherham United FC (ENG)"),
    ("Jearl Margaritha","FW","SK Beveren (BEL)"),
    ("Brandley Kuwas","FW","FC Volendam (NED)"),
    ("Armando Obispo","DF","PSV Eindhoven (NED)"),
    ("Gervane Kastaneer","FW","Terengganu FC (MAS)"),
    ("Joshua Brenet","DF","Kayserispor (TUR)"),
    ("Tahith Chong","MF","Sheffield United FC (ENG)"),
    ("Kevin Felida","MF","FC Den Bosch (NED)"),
    ("Riechedly Bazoer","DF","Konyaspor (TUR)"),
    ("Deveron Fonville","DF","NEC Nijmegen (NED)"),
    ("Tyrick Bodak","GK","SC Telstar (NED)"),
    ("Trevor Doornbusch","GK","VVV Venlo (NED)"),
]),

"cz": _squad([  # Tschechien
    ("Matej Kovar","GK","PSV Eindhoven (NED)"),
    ("David Zima","DF","SK Slavia Praha (CZE)"),
    ("Tomas Holes","DF","SK Slavia Praha (CZE)"),
    ("Robin Hranac","DF","TSG Hoffenheim (GER)"),
    ("Vladimir Coufal","DF","TSG Hoffenheim (GER)"),
    ("Stepan Chaloupek","DF","SK Slavia Praha (CZE)"),
    ("Ladislav Krejci","DF","Wolverhampton Wanderers FC (ENG)"),
    ("Vladimir Darida","MF","FC Hradec Králové (CZE)"),
    ("Adam Hlozek","FW","TSG Hoffenheim (GER)"),
    ("Patrik Schick","FW","Bayer Leverkusen (GER)"),
    ("Jan Kuchta","FW","AC Sparta Praha (CZE)"),
    ("Lukas Cerv","MF","FC Viktoria Plzeň (CZE)"),
    ("Mojmir Chytil","FW","SK Slavia Praha (CZE)"),
    ("David Jurasek","DF","SK Slavia Praha (CZE)"),
    ("Pavel Sulc","FW","Olympique Lyonnais (FRA)"),
    ("Jindrich Stanek","GK","SK Slavia Praha (CZE)"),
    ("Lukas Provod","MF","SK Slavia Praha (CZE)"),
    ("Michal Sadilek","MF","SK Slavia Praha (CZE)"),
    ("Tomas Chory","FW","SK Slavia Praha (CZE)"),
    ("Jaroslav Zeleny","DF","AC Sparta Praha (CZE)"),
    ("David Doudera","DF","SK Slavia Praha (CZE)"),
    ("Tomas Soucek","MF","West Ham United FC (ENG)"),
    ("Lukas Hornicek","GK","SC Braga (POR)"),
    ("Alexandr Sojka","MF","FC Viktoria Plzeň (CZE)"),
    ("Hugo Sochurek","MF","AC Sparta Praha (CZE)"),
    ("Denis Visinsky","FW","FC Viktoria Plzeň (CZE)"),
]),

"ec": _squad([  # Ecuador
    ("Hernan Galindez","GK","CA Huracán (ARG)"),
    ("Felix Torres","DF","SC Internacional (BRA)"),
    ("Piero Hincapie","DF","Arsenal FC (ENG)"),
    ("Joel Ordonez","DF","Club Brugge (BEL)"),
    ("Jordy Alcivar","MF","Independiente Del Valle (ECU)"),
    ("Willian Pacho","DF","Paris Saint-Germain (FRA)"),
    ("Pervis Estupinan","DF","AC Milan (ITA)"),
    ("Anthony Valencia","MF","Royal Antwerp FC (BEL)"),
    ("John Yeboah","FW","Venezia FC (ITA)"),
    ("Kendry Paez","MF","CA River Plate (ARG)"),
    ("Kevin Rodriguez","FW","Royale Union Saint-Gilloise (BEL)"),
    ("Moises Ramirez","GK","AE Kifisia FC (GRE)"),
    ("Enner Valencia","FW","CF Pachuca (MEX)"),
    ("Alan Minda","MF","Atlético Mineiro (BRA)"),
    ("Pedro Vite","MF","Pumas UNAM (MEX)"),
    ("Jordy Caicedo","FW","CA Huracán (ARG)"),
    ("Angelo Preciado","DF","Atlético Mineiro (BRA)"),
    ("Denil Castillo","MF","FC Midtjylland (DEN)"),
    ("Gonzalo Plata","FW","CR Flamengo (BRA)"),
    ("Nilson Angulo","FW","Sunderland AFC (ENG)"),
    ("Alan Franco","MF","Atlético Mineiro (BRA)"),
    ("Gonzalo Valle","GK","LDU Quito (ECU)"),
    ("Moises Caicedo","MF","Chelsea FC (ENG)"),
    ("Jeremy Arevalo","FW","VfB Stuttgart (GER)"),
    ("Jackson Porozo","DF","Club Tijuana (MEX)"),
    ("Yaimar Medina","DF","KRC Genk (BEL)"),
]),

"eg": _squad([  # Ägypten
    ("Mohamed Elshenawy","GK","Al Ahly FC (EGY)"),
    ("Yasser Ibrahim","DF","Al Ahly FC (EGY)"),
    ("Mohamed Hany","DF","Al Ahly FC (EGY)"),
    ("Hossam Abdelmaguid","DF","Zamalek SC (EGY)"),
    ("Ramy Rabia","DF","Al Ain FC (UAE)"),
    ("Mohamed Abdelmoneim","DF","OGC Nice (FRA)"),
    ("Mahmoud Trezeguet","FW","Al Ahly FC (EGY)"),
    ("Emam Ashour","MF","Al Ahly FC (EGY)"),
    ("Hamza Abdelkarim","FW","FC Barcelona (ESP)"),
    ("Mohamed Salah","FW","Liverpool FC (ENG)"),
    ("Mostafa Zico","FW","Pyramids FC (EGY)"),
    ("Haissem Hassan","FW","Real Oviedo (ESP)"),
    ("Ahmed Fatouh","DF","Zamalek SC (EGY)"),
    ("Hamdy Fathy","MF","Al Wakrah SC (QAT)"),
    ("Karim Hafez","DF","Pyramids FC (EGY)"),
    ("Mahdy Soliman","GK","Zamalek SC (EGY)"),
    ("Mohanad Lashin","MF","Pyramids FC (EGY)"),
    ("Nabil Donga","MF","Al Najmah SC (KSA)"),
    ("Marawan Attia","MF","Al Ahly FC (EGY)"),
    ("Ibrahim Adel","FW","FC Nordsjælland (DEN)"),
    ("Mahmoud Saber","MF","ZED FC (EGY)"),
    ("Omar Marmoush","FW","Manchester City FC (ENG)"),
    ("Mostafa Shoubir","GK","Al Ahly FC (EGY)"),
    ("Tarek Alaa","DF","ZED FC (EGY)"),
    ("Zizo","FW","Al Ahly FC (EGY)"),
    ("Mohamed Alaa","GK","El Gouna FC (EGY)"),
]),

"gb-eng": _squad([  # England
    ("Jordan Pickford","GK","Everton FC (ENG)"),
    ("Ezri Konsa","DF","Aston Villa FC (ENG)"),
    ("Nico O'Reilly","DF","Manchester City FC (ENG)"),
    ("Declan Rice","MF","Arsenal FC (ENG)"),
    ("John Stones","DF","Manchester City FC (ENG)"),
    ("Marc Guehi","DF","Manchester City FC (ENG)"),
    ("Bukayo Saka","FW","Arsenal FC (ENG)"),
    ("Elliot Anderson","MF","Nottingham Forest FC (ENG)"),
    ("Harry Kane","FW","FC Bayern München (GER)"),
    ("Jude Bellingham","MF","Real Madrid C. F. (ESP)"),
    ("Marcus Rashford","FW","FC Barcelona (ESP)"),
    ("Tino Livramento","DF","Newcastle United FC (ENG)"),
    ("Dean Henderson","GK","Crystal Palace FC (ENG)"),
    ("Jordan Henderson","MF","Brentford FC (ENG)"),
    ("Dan Burn","DF","Newcastle United FC (ENG)"),
    ("Kobbie Mainoo","MF","Manchester United FC (ENG)"),
    ("Morgan Rogers","MF","Aston Villa FC (ENG)"),
    ("Anthony Gordon","FW","Newcastle United FC (ENG)"),
    ("Ollie Watkins","FW","Aston Villa FC (ENG)"),
    ("Noni Madueke","FW","Arsenal FC (ENG)"),
    ("Eberechi Eze","MF","Arsenal FC (ENG)"),
    ("Ivan Toney","FW","Al Ahli FC (KSA)"),
    ("James Trafford","GK","Manchester City FC (ENG)"),
    ("Reece James","DF","Chelsea FC (ENG)"),
    ("Djed Spence","DF","Tottenham Hotspur FC (ENG)"),
    ("Jarell Quansah","DF","Bayer Leverkusen (GER)"),
]),

"fr": _squad([  # Frankreich
    ("Brice Samba","GK","Stade Rennais FC (FRA)"),
    ("Malo Gusto","DF","Chelsea FC (ENG)"),
    ("Lucas Digne","DF","Aston Villa FC (ENG)"),
    ("Dayot Upamecano","DF","FC Bayern München (GER)"),
    ("Jules Kounde","DF","FC Barcelona (ESP)"),
    ("Manu Kone","MF","AS Roma (ITA)"),
    ("Ousmane Dembele","FW","Paris Saint-Germain (FRA)"),
    ("Aurelien Tchouameni","MF","Real Madrid C. F. (ESP)"),
    ("Marcus Thuram","FW","FC Internazionale Milano (ITA)"),
    ("Kylian Mbappe","FW","Real Madrid C. F. (ESP)"),
    ("Michael Olise","FW","FC Bayern München (GER)"),
    ("Bradley Barcola","FW","Paris Saint-Germain (FRA)"),
    ("Ngolo Kante","MF","Fenerbahçe SK (TUR)"),
    ("Adrien Rabiot","MF","AC Milan (ITA)"),
    ("Ibrahima Konate","DF","Liverpool FC (ENG)"),
    ("Mike Maignan","GK","AC Milan (ITA)"),
    ("William Saliba","DF","Arsenal FC (ENG)"),
    ("Warren Zaire-Emery","MF","Paris Saint-Germain (FRA)"),
    ("Theo Hernandez","DF","Al Hilal SC (KSA)"),
    ("Desire Doue","FW","Paris Saint-Germain (FRA)"),
    ("Lucas Hernandez","DF","Paris Saint-Germain (FRA)"),
    ("Jean-Philippe Mateta","FW","Crystal Palace FC (ENG)"),
    ("Robin Risser","GK","RC Lens (FRA)"),
    ("Rayan Cherki","MF","Manchester City FC (ENG)"),
    ("Maghnes Akliouche","MF","AS Monaco (FRA)"),
    ("Maxence Lacroix","DF","Crystal Palace FC (ENG)"),
]),

"de": _squad([  # Deutschland
    ("Manuel Neuer","GK","FC Bayern München (GER)"),
    ("Antonio Ruediger","DF","Real Madrid C. F. (ESP)"),
    ("Waldemar Anton","DF","Borussia Dortmund (GER)"),
    ("Jonathan Tah","DF","FC Bayern München (GER)"),
    ("Aleksandar Pavlovic","MF","FC Bayern München (GER)"),
    ("Joshua Kimmich","DF","FC Bayern München (GER)"),
    ("Kai Havertz","FW","Arsenal FC (ENG)"),
    ("Leon Goretzka","MF","FC Bayern München (GER)"),
    ("Jamie Leweling","MF","VfB Stuttgart (GER)"),
    ("Jamal Musiala","MF","FC Bayern München (GER)"),
    ("Nick Woltemade","FW","Newcastle United FC (ENG)"),
    ("Oliver Baumann","GK","TSG Hoffenheim (GER)"),
    ("Pascal Gross","MF","Brighton & Hove Albion FC (ENG)"),
    ("Maximilian Beier","FW","Borussia Dortmund (GER)"),
    ("Nico Schlotterbeck","DF","Borussia Dortmund (GER)"),
    ("Angelo Stiller","MF","VfB Stuttgart (GER)"),
    ("Florian Wirtz","MF","Liverpool FC (ENG)"),
    ("Nathaniel Brown","DF","Eintracht Frankfurt (GER)"),
    ("Leroy Sane","MF","Galatasaray SK (TUR)"),
    ("Nadiem Amiri","MF","1. FSV Mainz 05 (GER)"),
    ("Alexander Nuebel","GK","VfB Stuttgart (GER)"),
    ("David Raum","DF","RB Leipzig (GER)"),
    ("Felix Nmecha","MF","Borussia Dortmund (GER)"),
    ("Malick Thiaw","DF","Newcastle United FC (ENG)"),
    ("Lennart Karl","MF","FC Bayern München (GER)"),
    ("Deniz Undav","FW","VfB Stuttgart (GER)"),
]),

"gh": _squad([  # Ghana
    ("Lawrence Ati Zigi","GK","FC St. Gallen (SUI)"),
    ("Alidu Seidu","DF","Stade Rennais FC (FRA)"),
    ("Caleb Yirenkyi","MF","FC Nordsjælland (DEN)"),
    ("Jonas Adjetey","DF","VfL Wolfsburg (GER)"),
    ("Thomas Partey","MF","Villarreal CF (ESP)"),
    ("Abdul Mumin","DF","Rayo Vallecano (ESP)"),
    ("Fatawu Issahaku","FW","Leicester City FC (ENG)"),
    ("Kwasi Sibo","MF","Real Oviedo (ESP)"),
    ("Jordan Ayew","FW","Leicester City FC (ENG)"),
    ("Brandon Thomas-Asante","FW","Coventry City FC (ENG)"),
    ("Antoine Semenyo","MF","Manchester City FC (ENG)"),
    ("Joseph Anang","GK","St Patrick's Athletic FC (IRL)"),
    ("Christopher Baah","FW","Al Qadsiah FC (KSA)"),
    ("Gideon Mensah","DF","AJ Auxerre (FRA)"),
    ("Elisha Owusu","MF","AJ Auxerre (FRA)"),
    ("Benjamin Asare","GK","Hearts Of Oak SC (GHA)"),
    ("Baba Rahman","DF","PAOK Saloniki (GRE)"),
    ("Jerome Opoku","DF","Başakşehir FK (TUR)"),
    ("Inaki Williams","FW","Athletic Club (ESP)"),
    ("Augustine Boakye","MF","AS Saint-Etienne (FRA)"),
    ("Kojo Oppong","DF","OGC Nice (FRA)"),
    ("Kamaldeen Sulemana","FW","Atalanta Bergamo (ITA)"),
    ("Derrick Luckassen","DF","Pafos FC (CYP)"),
    ("Ernest Nuamah","FW","Olympique Lyonnais (FRA)"),
    ("Prince Adu","FW","FC Viktoria Plzeň (CZE)"),
    ("Marvin Senaya","DF","AJ Auxerre (FRA)"),
]),

"ht": _squad([  # Haiti
    ("Johny Placide","GK","SC Bastia (FRA)"),
    ("Carlens Arcus","DF","Angers SCO (FRA)"),
    ("Keeto Thermoncy","DF","BSC Young Boys (SUI)"),
    ("Ricardo Ade","DF","LDU Quito (ECU)"),
    ("Hannes Delcroix","DF","FC Lugano (SUI)"),
    ("Carl Sainte","MF","El Paso Locomotive FC (USA)"),
    ("Derrick Etienne Jr.","FW","Toronto FC (CAN)"),
    ("Martin Experience","DF","AS Nancy (FRA)"),
    ("Duckens Nazon","FW","Esteghlal Tehran FC (IRN)"),
    ("Jean-Ricner Bellegarde","MF","Wolverhampton Wanderers FC (ENG)"),
    ("Louicius Deedson","FW","FC Dallas (USA)"),
    ("Alexandre Pierre","GK","FC Sochaux-Montbéliard (FRA)"),
    ("Markhus Lacroix","DF","Colorado Springs Switchbacks FC (USA)"),
    ("Leverton Pierre","MF","FC Vizela (POR)"),
    ("Ruben Providence","FW","Almere City FC (NED)"),
    ("Lenny Joseph","FW","Ferencvárosi TC (HUN)"),
    ("Danley Jean Jacques","MF","Philadelphia Union (USA)"),
    ("Wilson Isidor","FW","Sunderland AFC (ENG)"),
    ("Yassin Fortune","FW","FC Vizela (POR)"),
    ("Frantzdy Pierrot","FW","Çaykur Rizespor (TUR)"),
    ("Josue Casimir","FW","AJ Auxerre (FRA)"),
    ("Jean-Kevin Duverne","DF","KAA Gent (BEL)"),
    ("Josue Duverger","GK","FC Cosmos Koblenz (GER)"),
    ("Wilguens Paugain","DF","SV Zulte Waregem (BEL)"),
    ("Dominique Simon","MF","FC Tatran Prešov (SVK)"),
    ("Woodensky Pierre","MF","Violette AC (HAI)"),
]),

"ir": _squad([  # Iran
    ("Alireza Beiranvand","GK","Tractor Sazi Tabriz FC (IRN)"),
    ("Saleh Hardani","DF","Esteghlal Tehran FC (IRN)"),
    ("Ehsan Hajisafi","DF","Sepahan SC (IRN)"),
    ("Shoja Khalilzadeh","DF","Tractor Sazi Tabriz FC (IRN)"),
    ("Milad Mohammadi","DF","Persepolis FC (IRN)"),
    ("Saeid Ezatolahi","MF","Shabab Al Ahli Club (UAE)"),
    ("Alireza Jahanbakhsh","MF","FCV Dender EH (BEL)"),
    ("Mohammad Mohebbi","MF","FC Rostov (RUS)"),
    ("Mehdi Taremi","FW","Olympiacos FC (GRE)"),
    ("Mehdi Ghayedi","FW","Al Nasr SC (UAE)"),
    ("Ali Alipour","FW","Persepolis FC (IRN)"),
    ("Payam Niazmand","GK","Persepolis FC (IRN)"),
    ("Hossein Kanani","DF","Persepolis FC (IRN)"),
    ("Saman Ghoddos","MF","Al Ittihad Kalba SCC (UAE)"),
    ("Roozbeh Cheshmi","MF","Esteghlal Tehran FC (IRN)"),
    ("Mehdi Torabi","MF","Tractor Sazi Tabriz FC (IRN)"),
    ("Arya Yousefi","DF","Sepahan SC (IRN)"),
    ("Amirhossein Hosseinzadeh","FW","Tractor Sazi Tabriz FC (IRN)"),
    ("Ali Nemati","DF","Foolad Khuzestan FC (IRN)"),
    ("Shahriyar Moghanloo","FW","Al Ittihad Kalba SCC (UAE)"),
    ("Mohammad Ghorbani","MF","Al Wahda SC (UAE)"),
    ("Hossein Hosseini","GK","Sepahan SC (IRN)"),
    ("Ramin Rezaeian","DF","Foolad Khuzestan FC (IRN)"),
    ("Dennis Dargahi","FW","Standard Liège (BEL)"),
    ("Danial Iri","DF","Malavan Anzali FC (IRN)"),
    ("Amirmohammad Razaghinia","MF","Esteghlal Tehran FC (IRN)"),
]),

"iq": _squad([  # Irak
    ("Fahad Talib","GK","Al Talaba SC (IRQ)"),
    ("Rebin Ghareeb","DF","Port FC (THA)"),
    ("Hussein Ali","DF","Pogoń Szczecin (POL)"),
    ("Zaid Tahseen","DF","Pakhtakor Tashkent FK (UZB)"),
    ("Akam Hashim","DF","Al Zawra'a SC (IRQ)"),
    ("Munaf Younus","DF","Al Shorta SC (IRQ)"),
    ("Youssef Amyn","MF","AEK Larnaca FC (CYP)"),
    ("Ibrahim Bayesh","MF","Al Dhafra SCC (UAE)"),
    ("Ali Alhamadi","FW","Luton Town FC (ENG)"),
    ("Mohanad Ali","FW","Dibba FC (UAE)"),
    ("Ahmed Qasim","FW","Nashville SC (USA)"),
    ("Jalal Hassan","GK","Al Zawra'a SC (IRQ)"),
    ("Ali Yousif","FW","Al Talaba SC (IRQ)"),
    ("Zidane Iqbal","MF","FC Utrecht (NED)"),
    ("Ahmed Yahya","DF","Al Shorta SC (IRQ)"),
    ("Amir Alammari","MF","KS Cracovia (POL)"),
    ("Ali Jasim","FW","Al Najmah SC (KSA)"),
    ("Aymen Hussein","FW","Al Karma SC (IRQ)"),
    ("Kevin Yakob","MF","Aarhus GF (DEN)"),
    ("Aimar Sher","MF","Sarpsborg 08 FF (NOR)"),
    ("Marko Farji","FW","Venezia FC (ITA)"),
    ("Ahmed Basil","GK","Al Shorta SC (IRQ)"),
    ("Merchas Doski","DF","FC Viktoria Plzeň (CZE)"),
    ("Zaid Ismael","MF","Al Talaba SC (IRQ)"),
    ("Mustafa Saadoon","DF","Al Shorta SC (IRQ)"),
    ("Frans Putros","DF","Persib Bandung (IDN)"),
]),

"jp": _squad([  # Japan
    ("Zion Suzuki","GK","Parma (ITA)"),
    ("Yukinari Sugawara","DF","SV Werder Bremen (GER)"),
    ("Shogo Taniguchi","DF","Sint-Truiden VV (BEL)"),
    ("Kou Itakura","DF","AFC Ajax (NED)"),
    ("Yuto Nagatomo","DF","FC Tokyo (JPN)"),
    ("Wataru Endo","MF","Liverpool FC (ENG)"),
    ("Ao Tanaka","MF","Leeds United FC (ENG)"),
    ("Takefusa Kubo","MF","Real Sociedad (ESP)"),
    ("Keisuke Goto","FW","Sint-Truiden VV (BEL)"),
    ("Ritsu Doan","MF","Eintracht Frankfurt (GER)"),
    ("Daizen Maeda","MF","Celtic FC (SCO)"),
    ("Keisuke Osako","GK","Sanfrecce Hiroshima (JPN)"),
    ("Keito Nakamura","MF","Stade Reims (FRA)"),
    ("Junya Ito","MF","KRC Genk (BEL)"),
    ("Daichi Kamada","MF","Crystal Palace FC (ENG)"),
    ("Tsuyoshi Watanabe","DF","Feyenoord Rotterdam (NED)"),
    ("Yuito Suzuki","MF","SC Freiburg (GER)"),
    ("Ayase Ueda","FW","Feyenoord Rotterdam (NED)"),
    ("Koki Ogawa","FW","NEC Nijmegen (NED)"),
    ("Ayumu Seko","DF","Le Havre AC (FRA)"),
    ("Hiroki Ito","DF","FC Bayern München (GER)"),
    ("Takehiro Tomiyasu","DF","AFC Ajax (NED)"),
    ("Tomoki Hayakawa","GK","Kashima Antlers (JPN)"),
    ("Kaishu Sano","MF","1. FSV Mainz 05 (GER)"),
    ("Junnosuke Suzuki","DF","FC København (DEN)"),
    ("Kento Shiogai","FW","VfL Wolfsburg (GER)"),
]),

"jo": _squad([  # Jordanien
    ("Yazeed Abulaila","GK","Al Hussein SC (JOR)"),
    ("Mohammad Abuhasheesh","DF","Al Karma SC (IRQ)"),
    ("Abdallah Nasib","DF","Al Zawra'a SC (IRQ)"),
    ("Husam Abudahab","DF","Al Faisaly SC (JOR)"),
    ("Yazan Alarab","DF","FC Seoul (KOR)"),
    ("Amer Jamous","MF","Al Zawra'a SC (IRQ)"),
    ("Mohammad Abuzraiq","FW","Raja Casablanca (MAR)"),
    ("Noor Alrawabdeh","MF","Selangor FC (MAS)"),
    ("Ali Olwan","FW","Al Sailiya SC (QAT)"),
    ("Mousa Altamari","FW","Stade Rennais FC (FRA)"),
    ("Odeh Fakhoury","FW","Pyramids FC (EGY)"),
    ("Nour Baniateyah","GK","Al Faisaly SC (JOR)"),
    ("Mahmoud Almardi","FW","Al Hussein SC (JOR)"),
    ("Rajaei Ayed","MF","Al Hussein SC (JOR)"),
    ("Ibrahim Sadeh","MF","Al Karma SC (IRQ)"),
    ("Mohammad Abualnadi","DF","Selangor FC (MAS)"),
    ("Saleem Obaid","DF","Al Hussein SC (JOR)"),
    ("Ibrahim Sabra","FW","NK Lokomotiva Zagreb (CRO)"),
    ("Saed Alrosan","DF","Al Hussein SC (JOR)"),
    ("Mohannad Abutaha","MF","Al-Quwa Al-Jawiya (IRQ)"),
    ("Nizar Alrashdan","MF","Qatar SC (QAT)"),
    ("Abdallah Alfakhori","GK","Al Wahdat SC (JOR)"),
    ("Ehsan Haddad","DF","Al Hussein SC (JOR)"),
    ("Ali Azaizeh","FW","Al Shabab FC (KSA)"),
    ("Mohammad Aldaoud","MF","Al Wahdat SC (JOR)"),
    ("Anas Badawi","DF","Al Faisaly SC (JOR)"),
]),

"kr": _squad([  # Südkorea
    ("Kim Seunggyu","GK","FC Tokyo (JPN)"),
    ("Lee Hanbeom","DF","FC Midtjylland (DEN)"),
    ("Lee Gihyuk","MF","Gangwon FC (KOR)"),
    ("Kim Minjae","DF","FC Bayern München (GER)"),
    ("Kim Taehyeon","DF","Kashima Antlers (JPN)"),
    ("Hwang Inbeom","MF","Feyenoord Rotterdam (NED)"),
    ("Son Heungmin","FW","LAFC (USA)"),
    ("Paik Seungho","MF","Birmingham City FC (ENG)"),
    ("Cho Guesung","FW","FC Midtjylland (DEN)"),
    ("Lee Jaesung","MF","1. FSV Mainz 05 (GER)"),
    ("Hwang Heechan","FW","Wolverhampton Wanderers FC (ENG)"),
    ("Song Bumkeun","GK","Jeonbuk Hyundai Motors FC (KOR)"),
    ("Lee Taeseok","DF","FK Austria Wien (AUT)"),
    ("Cho Wije","DF","Jeonbuk Hyundai Motors FC (KOR)"),
    ("Kim Moonhwan","DF","Daejeon Hana Citizen FC (KOR)"),
    ("Park Jinseob","DF","Zhejiang FC (CHN)"),
    ("Bae Junho","MF","Stoke City FC (ENG)"),
    ("Oh Hyeongyu","FW","Beşiktaş JK (TUR)"),
    ("Lee Kangin","MF","Paris Saint-Germain (FRA)"),
    ("Yang Hyunjun","MF","Celtic FC (SCO)"),
    ("Jo Hyeonwoo","GK","Ulsan HD (KOR)"),
    ("Seol Youngwoo","DF","FK Crvena Zvezda (SRB)"),
    ("Jens Castrop","DF","Borussia Mönchengladbach (GER)"),
    ("Kim Jingyu","MF","Jeonbuk Hyundai Motors FC (KOR)"),
    ("Eom Jisung","MF","Swansea City AFC (WAL)"),
    ("Lee Donggyeong","MF","Ulsan HD (KOR)"),
]),

"mx": _squad([  # Mexiko
    ("Raul Rangel","GK","CD Guadalajara (MEX)"),
    ("Jorge Sanchez","DF","PAOK Saloniki (GRE)"),
    ("Cesar Montes","DF","FC Lokomotiv Moscow (RUS)"),
    ("Edson Alvarez","DF","Fenerbahçe SK (TUR)"),
    ("Johan Vasquez","DF","Genoa CFC (ITA)"),
    ("Erik Lira","MF","CF Cruz Azul (MEX)"),
    ("Luis Romo","MF","CD Guadalajara (MEX)"),
    ("Alvaro Fidalgo","MF","Real Betis (ESP)"),
    ("Raul Jimenez","FW","Fulham FC (ENG)"),
    ("Alexis Vega","FW","Deportivo Toluca FC (MEX)"),
    ("Santiago Gimenez","FW","AC Milan (ITA)"),
    ("Carlos Acevedo","GK","Club Santos Laguna (MEX)"),
    ("Guillermo Ochoa","GK","AEL Limassol (CYP)"),
    ("Armando Gonzalez","FW","CD Guadalajara (MEX)"),
    ("Israel Reyes","DF","Club América (MEX)"),
    ("Julian Quinones","FW","Al Qadsiah FC (KSA)"),
    ("Orbelin Pineda","MF","AEK Athens (GRE)"),
    ("Obed Vargas","MF","Atlético De Madrid (ESP)"),
    ("Gilberto Mora","MF","Club Tijuana (MEX)"),
    ("Mateo Chavez","DF","AZ Alkmaar (NED)"),
    ("Cesar Huerta","FW","RSC Anderlecht (BEL)"),
    ("Guillermo Martinez","FW","Pumas UNAM (MEX)"),
    ("Jesus Gallardo","DF","Deportivo Toluca FC (MEX)"),
    ("Luis Chavez","MF","FC Dynamo Moscow (RUS)"),
    ("Roberto Alvarado","FW","CD Guadalajara (MEX)"),
    ("Brian Gutierrez","MF","CD Guadalajara (MEX)"),
]),

"ma": _squad([  # Marokko
    ("Yassine Bounou","GK","Al Hilal SC (KSA)"),
    ("Achraf Hakimi","DF","Paris Saint-Germain (FRA)"),
    ("Noussair Mazraoui","DF","Manchester United FC (ENG)"),
    ("Sofyan Amrabat","MF","Real Betis (ESP)"),
    ("Nayef Aguerd","DF","Olympique Marseille (FRA)"),
    ("Ayyoub Bouaddi","MF","Lille OSC (FRA)"),
    ("Chemsdine Talbi","MF","Sunderland AFC (ENG)"),
    ("Azzedine Ounahi","MF","Girona FC (ESP)"),
    ("Souane Rahimi","FW","Al Ain FC (UAE)"),
    ("Brahim Diaz","FW","Real Madrid C. F. (ESP)"),
    ("Ismael Saibari","MF","PSV Eindhoven (NED)"),
    ("Munir El Kajoui","GK","RS Berkane (MAR)"),
    ("Zakaria El Ouahdi","DF","KRC Genk (BEL)"),
    ("Issa Diop","DF","Fulham FC (ENG)"),
    ("Samir El Mourabet","MF","RC Strasbourg (FRA)"),
    ("Gessime Yassine","MF","RC Strasbourg (FRA)"),
    ("Abde Ezzalzouli","FW","Real Betis (ESP)"),
    ("Chadi Riad","DF","Crystal Palace FC (ENG)"),
    ("Youssef Belammari","DF","Al Ahly FC (EGY)"),
    ("Ayoub El Kaabi","FW","Olympiacos FC (GRE)"),
    ("Ayoube Amaimouni","FW","Eintracht Frankfurt (GER)"),
    ("Ahmed Reda Tagnaouti","GK","ASFAR (MAR)"),
    ("Bilal El Khannouss","MF","VfB Stuttgart (GER)"),
    ("Neil El Aynaoui","MF","AS Roma (ITA)"),
    ("Redouane Halhal","DF","KV Mechelen (BEL)"),
    ("Anass Salah Eddine","DF","PSV Eindhoven (NED)"),
]),

"nl": _squad([  # Niederlande
    ("Bart Verbruggen","GK","Brighton & Hove Albion FC (ENG)"),
    ("Jurrien Timber","DF","Arsenal FC (ENG)"),
    ("Marten De Roon","MF","Atalanta Bergamo (ITA)"),
    ("Virgil Van Dijk","DF","Liverpool FC (ENG)"),
    ("Nathan Ake","DF","Manchester City FC (ENG)"),
    ("Jan-Paul Van Hecke","DF","Brighton & Hove Albion FC (ENG)"),
    ("Justin Kluivert","MF","AFC Bournemouth (ENG)"),
    ("Ryan Gravenberch","MF","Liverpool FC (ENG)"),
    ("Wout Weghorst","FW","AFC Ajax (NED)"),
    ("Memphis Depay","FW","SC Corinthians (BRA)"),
    ("Cody Gakpo","FW","Liverpool FC (ENG)"),
    ("Mats Wieffer","DF","Brighton & Hove Albion FC (ENG)"),
    ("Robin Roefs","GK","Sunderland AFC (ENG)"),
    ("Tijjani Reijnders","MF","Manchester City FC (ENG)"),
    ("Micky Van De Ven","DF","Tottenham Hotspur FC (ENG)"),
    ("Guus Til","MF","PSV Eindhoven (NED)"),
    ("Noa Lang","FW","Galatasaray SK (TUR)"),
    ("Donyell Malen","FW","AS Roma (ITA)"),
    ("Brian Brobbey","FW","Sunderland AFC (ENG)"),
    ("Teun Koopmeiners","MF","Juventus FC (ITA)"),
    ("Frenkie De Jong","MF","FC Barcelona (ESP)"),
    ("Denzel Dumfries","DF","FC Internazionale Milano (ITA)"),
    ("Mark Flekken","GK","Bayer Leverkusen (GER)"),
    ("Crysencio Summerville","FW","West Ham United FC (ENG)"),
    ("Jorrel Hato","DF","Chelsea FC (ENG)"),
    ("Quinten Timber","MF","Olympique Marseille (FRA)"),
]),

"nz": _squad([  # Neuseeland
    ("Max Crocombe","GK","Millwall FC (ENG)"),
    ("Tim Payne","DF","Wellington Phoenix FC (NZL)"),
    ("Francis De Vries","DF","Auckland FC (NZL)"),
    ("Tyler Bindon","DF","Sheffield United FC (ENG)"),
    ("Michael Boxall","DF","Minnesota United FC (USA)"),
    ("Joe Bell","MF","Viking Stavanger (NOR)"),
    ("Matthew Garbett","MF","Peterborough United FC (ENG)"),
    ("Marko Stamenic","MF","Swansea City AFC (WAL)"),
    ("Chris Wood","FW","Nottingham Forest FC (ENG)"),
    ("Sarpreet Singh","MF","Wellington Phoenix FC (NZL)"),
    ("Elijah Just","MF","Motherwell FC (SCO)"),
    ("Alex Paulsen","GK","Lechia Gdańsk (POL)"),
    ("Liberato Cacace","DF","Wrexham AFC (WAL)"),
    ("Alex Rufer","MF","Wellington Phoenix FC (NZL)"),
    ("Nando Pijnaker","DF","Auckland FC (NZL)"),
    ("Finn Surman","DF","Portland Timbers (USA)"),
    ("Kosta Barbarouses","FW","WS Wanderers FC (AUS)"),
    ("Ben Waine","FW","Port Vale FC (ENG)"),
    ("Ben Old","MF","AS Saint-Etienne (FRA)"),
    ("Callum McCowatt","MF","Silkeborg IF (DEN)"),
    ("Jesse Randall","FW","Auckland FC (NZL)"),
    ("Michael Woud","GK","Auckland FC (NZL)"),
    ("Ryan Thomas","MF","PEC Zwolle (NED)"),
    ("Callan Elliot","DF","Auckland FC (NZL)"),
    ("Lachlan Bayliss","MF","Newcastle United Jets FC (AUS)"),
    ("Tommy Smith","DF","Braintree Town FC (ENG)"),
]),

"no": _squad([  # Norwegen
    ("Orjan Nyland","GK","Sevilla FC (ESP)"),
    ("Morten Thorsby","MF","US Cremonese (ITA)"),
    ("Kristoffer Ajer","DF","Brentford FC (ENG)"),
    ("Leo Ostigard","DF","Genoa CFC (ITA)"),
    ("David Moller Wolfe","DF","Wolverhampton Wanderers FC (ENG)"),
    ("Patrick Berg","MF","FK Bodø/Glimt (NOR)"),
    ("Alexander Sorloth","FW","Atlético De Madrid (ESP)"),
    ("Sander Berge","MF","Fulham FC (ENG)"),
    ("Erling Haaland","FW","Manchester City FC (ENG)"),
    ("Martin Odegaard","MF","Arsenal FC (ENG)"),
    ("Jorgen Strand Larsen","FW","Crystal Palace FC (ENG)"),
    ("Sander Tangvik","GK","Hamburger SV (GER)"),
    ("Egil Selvik","GK","Watford FC (ENG)"),
    ("Fredrik Aursnes","MF","SL Benfica (POR)"),
    ("Fredrik Bjorkan","DF","FK Bodø/Glimt (NOR)"),
    ("Marcus Holmgren Pedersen","DF","Torino FC (ITA)"),
    ("Torbjorn Heggem","DF","Bologna FC (ITA)"),
    ("Kristian Thorstvedt","MF","US Sassuolo (ITA)"),
    ("Thelo Aasgaard","MF","Rangers FC (SCO)"),
    ("Antonio Nusa","FW","RB Leipzig (GER)"),
    ("Andreas Schjelderup","MF","SL Benfica (POR)"),
    ("Oscar Bobb","MF","Fulham FC (ENG)"),
    ("Jens Petter Hauge","MF","FK Bodø/Glimt (NOR)"),
    ("Sondre Langas","DF","Derby County FC (ENG)"),
    ("Henrik Falchener","DF","Viking Stavanger (NOR)"),
    ("Julian Ryerson","FW","Borussia Dortmund (GER)"),
]),

"pa": _squad([  # Panama
    ("Luis Mejia","GK","Club Nacional (URU)"),
    ("Cesar Blackman","DF","ŠK Slovan Bratislava (SVK)"),
    ("Jose Cordoba","DF","Norwich City FC (ENG)"),
    ("Fidel Escobar","DF","Deportivo Saprissa (CRC)"),
    ("Edgardo Farina","DF","FC Pari Nizhny Novgorod (RUS)"),
    ("Cristian Martinez","MF","Hapoel Kiryat Shmona FC (ISR)"),
    ("Jose Luis Rodriguez","MF","FC Juárez (MEX)"),
    ("Adalberto Carrasquilla","MF","Pumas UNAM (MEX)"),
    ("Tomas Rodriguez","FW","Deportivo Saprissa (CRC)"),
    ("Ismael Diaz","MF","Club León (MEX)"),
    ("Edgar Barcenas","MF","Mazatlán FC (MEX)"),
    ("Cesar Samudio","GK","CD Marathón (HON)"),
    ("Jiovany Ramos","DF","Puerto Cabello CF (VEN)"),
    ("Carlos Harvey","DF","Minnesota United FC (USA)"),
    ("Eric Davis","DF","CD Plaza Amador (PAN)"),
    ("Andres Andrade","DF","LASK Linz (AUT)"),
    ("Jose Fajardo","FW","CD Universidad Católica (ECU)"),
    ("Cecilio Waterman","FW","CD Universidad De Concepción (CHI)"),
    ("Alberto Quintero","MF","CD Plaza Amador (PAN)"),
    ("Anibal Godoy","MF","San Diego FC (USA)"),
    ("Cesar Yanis","MF","CD Cobresal (CHI)"),
    ("Orlando Mosquera","GK","Al Fayha FC (KSA)"),
    ("Amir Murillo","DF","Beşiktaş JK (TUR)"),
    ("Azarias Londono","FW","CD Universidad Católica (ECU)"),
    ("Roderick Miller","DF","Turan Tovuz (AZE)"),
    ("Jorge Gutierrez","DF","Deportivo La Guaira (VEN)"),
]),

"py": _squad([  # Paraguay
    ("Gatito Fernandez","GK","Cerro Porteño (PAR)"),
    ("Gustavo Velazquez","DF","Cerro Porteño (PAR)"),
    ("Omar Alderete","DF","Sunderland AFC (ENG)"),
    ("Juan Jose Caceres","DF","FC Dynamo Moscow (RUS)"),
    ("Fabian Balbuena","DF","Grêmio FBPA (BRA)"),
    ("Junior Alonso","DF","Atlético Mineiro (BRA)"),
    ("Ramon Sosa","MF","SE Palmeiras (BRA)"),
    ("Diego Gomez","MF","Brighton & Hove Albion FC (ENG)"),
    ("Antonio Sanabria","FW","US Cremonese (ITA)"),
    ("Miguel Almiron","MF","Atlanta United FC (USA)"),
    ("Mauricio","MF","SE Palmeiras (BRA)"),
    ("Orlando Gill","GK","CA San Lorenzo (ARG)"),
    ("Jose Canale","DF","CA Lanús (ARG)"),
    ("Andres Cubas","MF","Vancouver Whitecaps FC (CAN)"),
    ("Gustavo Gomez","DF","SE Palmeiras (BRA)"),
    ("Damian Bobadilla","MF","São Paulo FC (BRA)"),
    ("Alejandro Romero Gamarra","FW","Al Ain FC (UAE)"),
    ("Alex Arce","FW","CS Independiente Rivadavia (ARG)"),
    ("Julio Enciso","FW","RC Strasbourg (FRA)"),
    ("Braian Ojeda","MF","Orlando City SC (USA)"),
    ("Gabriel Avalos","FW","CA Independiente (ARG)"),
    ("Gaston Olveira","GK","Club Olimpia (PAR)"),
    ("Matias Galarza","MF","Atlanta United FC (USA)"),
    ("Gustavo Caballero","MF","Portsmouth FC (ENG)"),
    ("Isidro Pitta","FW","Red Bull Bragantino (BRA)"),
    ("Alexandro Maidana","DF","CA Talleres (ARG)"),
]),

"pt": _squad([  # Portugal
    ("Diogo Costa","GK","FC Porto (POR)"),
    ("Nelson Semedo","DF","Fenerbahçe SK (TUR)"),
    ("Ruben Dias","DF","Manchester City FC (ENG)"),
    ("Tomas Araujo","DF","SL Benfica (POR)"),
    ("Diogo Dalot","DF","Manchester United FC (ENG)"),
    ("Matheus Nunes","MF","Manchester City FC (ENG)"),
    ("Cristiano Ronaldo","FW","Al Nassr FC (KSA)"),
    ("Bruno Fernandes","MF","Manchester United FC (ENG)"),
    ("Goncalo Ramos","FW","Paris Saint-Germain (FRA)"),
    ("Bernardo Silva","MF","Manchester City FC (ENG)"),
    ("Joao Felix","FW","Al Nassr FC (KSA)"),
    ("Jose Sa","GK","Wolverhampton Wanderers FC (ENG)"),
    ("Renato Veiga","DF","Villarreal CF (ESP)"),
    ("Goncalo Inacio","DF","Sporting CP (POR)"),
    ("Joao Neves","MF","Paris Saint-Germain (FRA)"),
    ("Francisco Trincao","FW","Sporting CP (POR)"),
    ("Rafael Leao","FW","AC Milan (ITA)"),
    ("Pedro Neto","FW","Chelsea FC (ENG)"),
    ("Goncalo Guedes","FW","Real Sociedad (ESP)"),
    ("Joao Cancelo","DF","FC Barcelona (ESP)"),
    ("Ruben Neves","MF","Al Hilal SC (KSA)"),
    ("Rui Silva","GK","Sporting CP (POR)"),
    ("Vitinha","MF","Paris Saint-Germain (FRA)"),
    ("Samu Costa","DF","RCD Mallorca (ESP)"),
    ("Nuno Mendes","DF","Paris Saint-Germain (FRA)"),
    ("Francisco Conceicao","FW","Juventus FC (ITA)"),
]),

"qa": _squad([  # Katar
    ("Mahmoud Abunada","GK","Al Rayyan SC (QAT)"),
    ("Pedro Miguel","DF","Al Sadd SC (QAT)"),
    ("Lucas Mendes","DF","Al Wakrah SC (QAT)"),
    ("Issa Laye","DF","Al Arabi SC (QAT)"),
    ("Jassem Gaber","DF","Al Rayyan SC (QAT)"),
    ("Abdulaziz Hatem","MF","Al Rayyan SC (QAT)"),
    ("Ahmed Alaaeldin","FW","Al Rayyan SC (QAT)"),
    ("Edmilson Junior","FW","Al Duhail SC (QAT)"),
    ("Mohammed Muntari","FW","Al Gharafa SC (QAT)"),
    ("Hassan Alhaydos","FW","Al Sadd SC (QAT)"),
    ("Akram Afif","FW","Al Sadd SC (QAT)"),
    ("Karim Boudiaf","MF","Al Duhail SC (QAT)"),
    ("Ayoub Aloui","DF","Al Gharafa SC (QAT)"),
    ("Homam Ahmed","DF","Cultural Leonesa (ESP)"),
    ("Yusuf Abdurisag","FW","Al Wakrah SC (QAT)"),
    ("Boualem Khoukhi","DF","Al Sadd SC (QAT)"),
    ("Ahmed Alganehi","MF","Al Gharafa SC (QAT)"),
    ("Sultan Albrake","DF","Al Duhail SC (QAT)"),
    ("Almoez Ali","FW","Al Duhail SC (QAT)"),
    ("Ahmed Fathy","MF","Al Arabi SC (QAT)"),
    ("Salah Zakaria","GK","Al Duhail SC (QAT)"),
    ("Meshaal Barsham","GK","Al Sadd SC (QAT)"),
    ("Assim Madibo","MF","Al Wakrah SC (QAT)"),
    ("Tahsin Jamshid","FW","Al Duhail SC (QAT)"),
    ("Alhashmi Alhussein","DF","Al Arabi SC (QAT)"),
    ("Mohamed Manai","FW","Al Shamal SC (QAT)"),
]),

"sa": _squad([  # Saudi-Arabien
    ("Nawaf Alaqidi","GK","Al Nassr FC (KSA)"),
    ("Ali Majrashi","DF","Al Ahli FC (KSA)"),
    ("Ali Lajami","DF","Al Hilal SC (KSA)"),
    ("Abdulelah Alamri","DF","Al Nassr FC (KSA)"),
    ("Hassan Altambakti","DF","Al Hilal SC (KSA)"),
    ("Nasser Aldawsari","MF","Al Hilal SC (KSA)"),
    ("Musab Aljuwayr","MF","Al Qadsiah FC (KSA)"),
    ("Aiman Yahya","FW","Al Nassr FC (KSA)"),
    ("Feras Albrikan","FW","Al Ahli FC (KSA)"),
    ("Salem Aldawsari","FW","Al Hilal SC (KSA)"),
    ("Saleh Alshehri","FW","Al Ittihad (KSA)"),
    ("Saud Abdulhamid","DF","RC Lens (FRA)"),
    ("Nawaf Bu Washl","DF","Al Nassr FC (KSA)"),
    ("Hassan Kadish","DF","Al Ittihad (KSA)"),
    ("Abdullah Alkhaibari","MF","Al Nassr FC (KSA)"),
    ("Ziyad Aljohani","MF","Al Ahli FC (KSA)"),
    ("Khalid Alghannam","FW","Al Ettifaq FC (KSA)"),
    ("Ala Alhajji","MF","Neom SC (KSA)"),
    ("Abdullah Alhamddan","FW","Al Nassr FC (KSA)"),
    ("Sultan Mandash","FW","Al Hilal SC (KSA)"),
    ("Mohammed Alowais","GK","Al Ula Saudi FC (KSA)"),
    ("Ahmed Alkassar","GK","Al Qadsiah FC (KSA)"),
    ("Mohamed Kanno","MF","Al Hilal SC (KSA)"),
    ("Moteb Alharbi","DF","Al Hilal SC (KSA)"),
    ("Jehad Thikri","DF","Al Qadsiah FC (KSA)"),
    ("Mohammed Abu Alshamat","DF","Al Qadsiah FC (KSA)"),
]),

"gb-sct": _squad([  # Schottland
    ("Angus Gunn","GK","Nottingham Forest FC (ENG)"),
    ("Aaron Hickey","DF","Brentford FC (ENG)"),
    ("Andy Robertson","DF","Liverpool FC (ENG)"),
    ("Scott McTominay","MF","SSC Napoli (ITA)"),
    ("Grant Hanley","DF","Hibernian FC (SCO)"),
    ("Kieran Tierney","DF","Celtic FC (SCO)"),
    ("John McGinn","MF","Aston Villa FC (ENG)"),
    ("Tyler Fletcher","MF","Manchester United FC (ENG)"),
    ("Lyndon Dykes","FW","Charlton Athletic FC (ENG)"),
    ("Che Adams","FW","Torino FC (ITA)"),
    ("Ryan Christie","MF","AFC Bournemouth (ENG)"),
    ("Liam Kelly","GK","Rangers FC (SCO)"),
    ("Jack Hendry","DF","Al Ettifaq FC (KSA)"),
    ("Ross Stewart","FW","Southampton FC (ENG)"),
    ("John Souttar","DF","Rangers FC (SCO)"),
    ("Dominic Hyam","DF","Wrexham AFC (WAL)"),
    ("Ben Gannon-Doak","FW","AFC Bournemouth (ENG)"),
    ("George Hirst","FW","Ipswich Town FC (ENG)"),
    ("Lewis Ferguson","MF","Bologna FC (ITA)"),
    ("Lawrence Shankland","FW","Heart Of Midlothian FC (SCO)"),
    ("Craig Gordon","GK","Heart Of Midlothian FC (SCO)"),
    ("Nathan Patterson","DF","Everton FC (ENG)"),
    ("Kenny McLean","MF","Norwich City FC (ENG)"),
    ("Anthony Ralston","DF","Celtic FC (SCO)"),
    ("Findlay Curtis","FW","Kilmarnock FC (SCO)"),
    ("Scott McKenna","DF","GNK Dinamo Zagreb (CRO)"),
]),

"sn": _squad([  # Senegal
    ("Yehvann Diouf","GK","OGC Nice (FRA)"),
    ("Mamadou Sarr","DF","Chelsea FC (ENG)"),
    ("Kalidou Koulibaly","DF","Al Hilal SC (KSA)"),
    ("Abdoulaye Seck","DF","Maccabi Haifa FC (ISR)"),
    ("Idrissa Gueye","MF","Everton FC (ENG)"),
    ("Pathe Ciss","MF","Rayo Vallecano (ESP)"),
    ("Assane Diao","FW","Como (ITA)"),
    ("Lamine Camara","MF","AS Monaco (FRA)"),
    ("Bamba Dieng","FW","FC Lorient (FRA)"),
    ("Sadio Mane","FW","Al Nassr FC (KSA)"),
    ("Nicolas Jackson","FW","FC Bayern München (GER)"),
    ("Cherif Ndiaye","FW","Samsunspor (TUR)"),
    ("Iliman Ndiaye","FW","Everton FC (ENG)"),
    ("Ismail Jakobs","DF","Galatasaray SK (TUR)"),
    ("Krepin Diatta","DF","AS Monaco (FRA)"),
    ("Edouard Mendy","GK","Al Ahli FC (KSA)"),
    ("Pape Matar Sarr","MF","Tottenham Hotspur FC (ENG)"),
    ("Ismaila Sarr","FW","Crystal Palace FC (ENG)"),
    ("Moussa Niakhate","DF","Olympique Lyonnais (FRA)"),
    ("Ibrahim Mbaye","FW","Paris Saint-Germain (FRA)"),
    ("Habib Diarra","MF","Sunderland AFC (ENG)"),
    ("Bara Ndiaye","MF","FC Bayern München (GER)"),
    ("Mory Diaw","GK","Le Havre AC (FRA)"),
    ("Antoine Mendy","DF","OGC Nice (FRA)"),
    ("El Hadji Malick Diouf","DF","West Ham United FC (ENG)"),
    ("Pape Gueye","MF","Villarreal CF (ESP)"),
]),

"za": _squad([  # Südafrika
    ("Ronwen Williams","GK","Mamelodi Sundowns FC (RSA)"),
    ("Thabang Matuludi","DF","Polokwane City FC (RSA)"),
    ("Khulumani Ndamane","DF","Mamelodi Sundowns FC (RSA)"),
    ("Teboho Mokoena","MF","Mamelodi Sundowns FC (RSA)"),
    ("Thalente Mbatha","MF","Orlando Pirates FC (RSA)"),
    ("Aubrey Modiba","DF","Mamelodi Sundowns FC (RSA)"),
    ("Oswin Appollis","FW","Orlando Pirates FC (RSA)"),
    ("Tshepang Moremi","FW","Orlando Pirates FC (RSA)"),
    ("Lyle Foster","FW","Burnley FC (ENG)"),
    ("Relebohile Mofokeng","FW","Orlando Pirates FC (RSA)"),
    ("Themba Zwane","MF","Mamelodi Sundowns FC (RSA)"),
    ("Thapelo Maseko","FW","AEL Limassol (CYP)"),
    ("Sphephelo Sithole","MF","CD Tondela (POR)"),
    ("Mbekezeli Mbokazi","DF","Chicago Fire FC (USA)"),
    ("Iqraam Rayners","FW","Mamelodi Sundowns FC (RSA)"),
    ("Sipho Chaine","GK","Orlando Pirates FC (RSA)"),
    ("Evidence Makgopa","FW","Orlando Pirates FC (RSA)"),
    ("Samukelo Kabini","DF","Molde FK (NOR)"),
    ("Nkosinathi Sibisi","DF","Orlando Pirates FC (RSA)"),
    ("Khuliso Mudau","DF","Mamelodi Sundowns FC (RSA)"),
    ("Ime Okon","DF","Hannover 96 (GER)"),
    ("Ricardo Goss","GK","Siwelele FC (RSA)"),
    ("Jayden Adams","MF","Mamelodi Sundowns FC (RSA)"),
    ("Olwethu Makhanya","DF","Philadelphia Union (USA)"),
    ("Kamogelo Sebelebele","FW","Orlando Pirates FC (RSA)"),
    ("Bradley Cross","DF","Kaizer Chiefs FC (RSA)"),
]),

"es": _squad([  # Spanien
    ("David Raya","GK","Arsenal FC (ENG)"),
    ("Marc Pubill","DF","Atlético De Madrid (ESP)"),
    ("Alex Grimaldo","DF","Bayer Leverkusen (GER)"),
    ("Eric Garcia","DF","FC Barcelona (ESP)"),
    ("Marcos Llorente","MF","Atlético De Madrid (ESP)"),
    ("Mikel Merino","MF","Arsenal FC (ENG)"),
    ("Ferran Torres","FW","FC Barcelona (ESP)"),
    ("Fabian Ruiz","MF","Paris Saint-Germain (FRA)"),
    ("Gavi","MF","FC Barcelona (ESP)"),
    ("Dani Olmo","FW","FC Barcelona (ESP)"),
    ("Yeremy Pino","FW","Crystal Palace FC (ENG)"),
    ("Pedro Porro","DF","Tottenham Hotspur FC (ENG)"),
    ("Joan Garcia","GK","FC Barcelona (ESP)"),
    ("Aymeric Laporte","DF","Athletic Club (ESP)"),
    ("Alex Baena","MF","Atlético De Madrid (ESP)"),
    ("Rodri","MF","Manchester City FC (ENG)"),
    ("Nico Williams","FW","Athletic Club (ESP)"),
    ("Martin Zubimendi","MF","Arsenal FC (ENG)"),
    ("Lamine Yamal","FW","FC Barcelona (ESP)"),
    ("Pedri","MF","FC Barcelona (ESP)"),
    ("Mikel Oyarzabal","FW","Real Sociedad (ESP)"),
    ("Pau Cubarsi","DF","FC Barcelona (ESP)"),
    ("Unai Simon","GK","Athletic Club (ESP)"),
    ("Marc Cucurella","DF","Chelsea FC (ENG)"),
    ("Victor Munoz","FW","CA Osasuna (ESP)"),
    ("Borja Iglesias","FW","RC Celta Vigo (ESP)"),
]),

"se": _squad([  # Schweden
    ("Jacob Widell Zetterstrom","GK","Derby County FC (ENG)"),
    ("Gustaf Lagerbielke","DF","SC Braga (POR)"),
    ("Victor Lindelof","DF","Aston Villa FC (ENG)"),
    ("Isak Hien","DF","Atalanta Bergamo (ITA)"),
    ("Gabriel Gudmundsson","DF","Leeds United FC (ENG)"),
    ("Herman Johansson","DF","FC Dallas (USA)"),
    ("Lucas Bergvall","MF","Tottenham Hotspur FC (ENG)"),
    ("Daniel Svensson","DF","Borussia Dortmund (GER)"),
    ("Alexander Isak","FW","Liverpool FC (ENG)"),
    ("Benjamin Nygren","MF","Celtic FC (SCO)"),
    ("Anthony Elanga","FW","Newcastle United FC (ENG)"),
    ("Viktor Johansson","GK","Stoke City FC (ENG)"),
    ("Ken Sema","MF","Pafos FC (CYP)"),
    ("Hjalmar Ekdal","DF","Burnley FC (ENG)"),
    ("Carl Starfelt","DF","RC Celta Vigo (ESP)"),
    ("Jesper Karlstrom","MF","Udinese (ITA)"),
    ("Viktor Gyokeres","FW","Arsenal FC (ENG)"),
    ("Yasin Ayari","MF","Brighton & Hove Albion FC (ENG)"),
    ("Mattias Svanberg","MF","VfL Wolfsburg (GER)"),
    ("Eric Smith","DF","FC St. Pauli (GER)"),
    ("Alexander Bernhardsson","DF","Holstein Kiel (GER)"),
    ("Besfort Zeneli","MF","Royale Union Saint-Gilloise (BEL)"),
    ("Kristoffer Nordfeldt","GK","AIK Stockholm (SWE)"),
    ("Elliot Stroud","DF","Mjällby AIF (SWE)"),
    ("Gustaf Nilsson","FW","Club Brugge (BEL)"),
    ("Taha Ali","FW","Malmö FF (SWE)"),
]),

"ch": _squad([  # Schweiz
    ("Gregor Kobel","GK","Borussia Dortmund (GER)"),
    ("Miro Muheim","DF","Hamburger SV (GER)"),
    ("Silvan Widmer","DF","1. FSV Mainz 05 (GER)"),
    ("Nico Elvedi","DF","Borussia Mönchengladbach (GER)"),
    ("Manuel Akanji","DF","FC Internazionale Milano (ITA)"),
    ("Denis Zakaria","MF","AS Monaco (FRA)"),
    ("Breel Embolo","FW","Stade Rennais FC (FRA)"),
    ("Remo Freuler","MF","Bologna FC (ITA)"),
    ("Johan Manzambi","MF","SC Freiburg (GER)"),
    ("Granit Xhaka","MF","Sunderland AFC (ENG)"),
    ("Dan Ndoye","FW","Nottingham Forest FC (ENG)"),
    ("Yvon Mvogo","GK","FC Lorient (FRA)"),
    ("Ricardo Rodriguez","DF","Real Betis (ESP)"),
    ("Ardon Jashari","MF","AC Milan (ITA)"),
    ("Djibril Sow","MF","Sevilla FC (ESP)"),
    ("Christian Fassnacht","FW","BSC Young Boys (SUI)"),
    ("Ruben Vargas","FW","Sevilla FC (ESP)"),
    ("Eray Coemert","DF","Valencia CF (ESP)"),
    ("Noah Okafor","FW","Leeds United FC (ENG)"),
    ("Michel Aebischer","MF","Pisa SC (ITA)"),
    ("Marvin Keller","GK","BSC Young Boys (SUI)"),
    ("Fabian Rieder","MF","FC Augsburg (GER)"),
    ("Zeki Amdouni","FW","Burnley FC (ENG)"),
    ("Aurele Amenda","DF","Eintracht Frankfurt (GER)"),
    ("Luca Jaquez","DF","VfB Stuttgart (GER)"),
    ("Cedric Itten","FW","Fortuna Düsseldorf (GER)"),
]),

"tn": _squad([  # Tunesien
    ("Mouhib Chamakh","GK","Club Africain (TUN)"),
    ("Ali Abdi","DF","OGC Nice (FRA)"),
    ("Montassar Talbi","DF","FC Lorient (FRA)"),
    ("Omar Rekik","DF","NK Maribor (SVN)"),
    ("Adam Arous","DF","Kasımpaşa SK (TUR)"),
    ("Dylan Bronn","DF","Servette FC (SUI)"),
    ("Elias Achouri","FW","FC København (DEN)"),
    ("Elias Saad","FW","Hannover 96 (GER)"),
    ("Hazem Mastouri","FW","FC Dynamo Makhachkala (RUS)"),
    ("Hannibal Mejbri","MF","Burnley FC (ENG)"),
    ("Ismael Gharbi","MF","FC Augsburg (GER)"),
    ("Mortadha Ben Ouanes","DF","Kasımpaşa SK (TUR)"),
    ("Rani Khedira","MF","1. FC Union Berlin (GER)"),
    ("Khalil Ayari","MF","Paris Saint-Germain (FRA)"),
    ("Mohamed Hadj Mahmoud","MF","FC Lugano (SUI)"),
    ("Aymen Dahmen","GK","CS Sfaxien (TUN)"),
    ("Ellyes Skhiri","MF","Eintracht Frankfurt (GER)"),
    ("Rayan Elloumi","FW","Vancouver Whitecaps FC (CAN)"),
    ("Firas Chaouat","FW","Club Africain (TUN)"),
    ("Yan Valery","DF","BSC Young Boys (SUI)"),
    ("Mohamed Amine Ben Hmida","DF","Espérance De Tunisie (TUN)"),
    ("Sabri Ben Hessen","GK","Étoile Du Sahel (TUN)"),
    ("Moutaz Neffati","DF","IFK Norrköping FK (SWE)"),
    ("Raed Chikhaoui","DF","US Monastir (TUN)"),
    ("Anis Slimane","MF","Norwich City FC (ENG)"),
    ("Sebastian Tounekti","MF","Celtic FC (SCO)"),
]),

"tr": _squad([  # Türkei
    ("Mert Gunok","GK","Fenerbahçe SK (TUR)"),
    ("Zeki Celik","DF","AS Roma (ITA)"),
    ("Merih Demiral","DF","Al Ahli FC (KSA)"),
    ("Caglar Soyuncu","DF","Fenerbahçe SK (TUR)"),
    ("Salih Ozcan","MF","Borussia Dortmund (GER)"),
    ("Orkun Kokcu","MF","Beşiktaş JK (TUR)"),
    ("Kerem Akturkoglu","FW","Fenerbahçe SK (TUR)"),
    ("Arda Guler","FW","Real Madrid C. F. (ESP)"),
    ("Deniz Gul","FW","FC Porto (POR)"),
    ("Hakan Calhanoglu","MF","FC Internazionale Milano (ITA)"),
    ("Kenan Yildiz","FW","Juventus FC (ITA)"),
    ("Altay Bayindir","GK","Manchester United FC (ENG)"),
    ("Eren Elmali","DF","Galatasaray SK (TUR)"),
    ("Abdulkerim Bardakci","DF","Galatasaray SK (TUR)"),
    ("Ozan Kabak","DF","TSG Hoffenheim (GER)"),
    ("Ismail Yuksek","MF","Fenerbahçe SK (TUR)"),
    ("Irfan Can Kahveci","FW","Kasımpaşa SK (TUR)"),
    ("Mert Muldur","DF","Fenerbahçe SK (TUR)"),
    ("Yunus Akgun","FW","Galatasaray SK (TUR)"),
    ("Ferdi Kadioglu","DF","Brighton & Hove Albion FC (ENG)"),
    ("Baris Alper Yilmaz","FW","Galatasaray SK (TUR)"),
    ("Kaan Ayhan","MF","Galatasaray SK (TUR)"),
    ("Ugurcan Cakir","GK","Galatasaray SK (TUR)"),
    ("Oguz Aydin","FW","Fenerbahçe SK (TUR)"),
    ("Samet Akaydin","DF","Çaykur Rizespor (TUR)"),
    ("Can Uzun","FW","Eintracht Frankfurt (GER)"),
]),

"uy": _squad([  # Uruguay
    ("Sergio Rochet","GK","SC Internacional (BRA)"),
    ("Jose Maria Gimenez","DF","Atlético De Madrid (ESP)"),
    ("Sebastian Caceres","DF","Club América (MEX)"),
    ("Ronald Araujo","DF","FC Barcelona (ESP)"),
    ("Manuel Ugarte","MF","Manchester United FC (ENG)"),
    ("Rodrigo Bentancur","MF","Tottenham Hotspur FC (ENG)"),
    ("Nicolas De La Cruz","MF","CR Flamengo (BRA)"),
    ("Federico Valverde","MF","Real Madrid C. F. (ESP)"),
    ("Darwin Nunez","FW","Al Hilal SC (KSA)"),
    ("Giorgian De Arrascaeta","MF","CR Flamengo (BRA)"),
    ("Facundo Pellistri","FW","Panathinaikos FC (GRE)"),
    ("Santiago Mele","GK","CF Monterrey (MEX)"),
    ("Guillermo Varela","DF","CR Flamengo (BRA)"),
    ("Agustin Canobbio","MF","Fluminense FC (BRA)"),
    ("Emiliano Martinez","MF","SE Palmeiras (BRA)"),
    ("Mathias Olivera","DF","SSC Napoli (ITA)"),
    ("Matias Vina","DF","CA River Plate (ARG)"),
    ("Brian Rodriguez","FW","Club América (MEX)"),
    ("Rodrigo Aguirre","FW","Tigres UANL (MEX)"),
    ("Maxi Araujo","MF","Sporting CP (POR)"),
    ("Federico Vinas","FW","Real Oviedo (ESP)"),
    ("Joaquin Piquerez","MF","SE Palmeiras (BRA)"),
    ("Fernando Muslera","GK","Estudiantes LP (ARG)"),
    ("Santiago Bueno","DF","Wolverhampton Wanderers FC (ENG)"),
    ("Juan Manuel Sanabria","MF","Real Salt Lake (USA)"),
    ("Rodrigo Zalazar","MF","SC Braga (POR)"),
]),

"us": _squad([  # USA
    ("Matt Turner","GK","New England Revolution (USA)"),
    ("Sergino Dest","DF","PSV Eindhoven (NED)"),
    ("Chris Richards","DF","Crystal Palace FC (ENG)"),
    ("Tyler Adams","MF","AFC Bournemouth (ENG)"),
    ("Antonee Robinson","DF","Fulham FC (ENG)"),
    ("Auston Trusty","DF","Celtic FC (SCO)"),
    ("Giovanni Reyna","MF","Borussia Mönchengladbach (GER)"),
    ("Weston McKennie","MF","Juventus FC (ITA)"),
    ("Ricardo Pepi","FW","PSV Eindhoven (NED)"),
    ("Christian Pulisic","FW","AC Milan (ITA)"),
    ("Brenden Aaronson","FW","Leeds United FC (ENG)"),
    ("Miles Robinson","DF","FC Cincinnati (USA)"),
    ("Tim Ream","DF","Charlotte FC (USA)"),
    ("Sebastian Berhalter","MF","Vancouver Whitecaps FC (CAN)"),
    ("Cristian Roldan","MF","Seattle Sounders FC (USA)"),
    ("Alex Freeman","DF","Villarreal CF (ESP)"),
    ("Malik Tillman","MF","Bayer Leverkusen (GER)"),
    ("Max Arfsten","DF","Columbus Crew (USA)"),
    ("Haji Wright","FW","Coventry City FC (ENG)"),
    ("Folarin Balogun","FW","AS Monaco (FRA)"),
    ("Timothy Weah","FW","Olympique Marseille (FRA)"),
    ("Mark McKenzie","DF","Toulouse FC (FRA)"),
    ("Joe Scally","DF","Borussia Mönchengladbach (GER)"),
    ("Matt Freese","GK","New York City FC (USA)"),
    ("Chris Brady","GK","Chicago Fire FC (USA)"),
    ("Alex Zendejas","FW","Club América (MEX)"),
]),

"uz": _squad([  # Usbekistan
    ("Utkir Yusupov","GK","PFC Navbahor Namangan (UZB)"),
    ("Abdukodir Khusanov","DF","Manchester City FC (ENG)"),
    ("Khojiakbar Alijonov","DF","Pakhtakor Tashkent FK (UZB)"),
    ("Farrukh Sayfiev","DF","FK Neftchi Farg'ona (UZB)"),
    ("Rustam Ashurmatov","DF","Esteghlal Tehran FC (IRN)"),
    ("Akmal Mozgovoy","MF","Pakhtakor Tashkent FK (UZB)"),
    ("Otabek Shukurov","MF","Baniyas Club (UAE)"),
    ("Jamshid Iskanderov","MF","FK Neftchi Farg'ona (UZB)"),
    ("Odiljon Xamrobekov","MF","Tractor Sazi Tabriz FC (IRN)"),
    ("Jaloliddin Masharipov","MF","Esteghlal Tehran FC (IRN)"),
    ("Oston Urunov","MF","Persepolis FC (IRN)"),
    ("Abduvohid Nematov","GK","Nasaf Qarshi FC (UZB)"),
    ("Sherzod Nasrullaev","DF","Pakhtakor Tashkent FK (UZB)"),
    ("Eldor Shomurodov","FW","Başakşehir FK (TUR)"),
    ("Umar Eshmurodov","DF","Nasaf Qarshi FC (UZB)"),
    ("Botirali Ergashev","GK","FK Neftchi Farg'ona (UZB)"),
    ("Dostonbek Khamdamov","MF","Pakhtakor Tashkent FK (UZB)"),
    ("Abdulla Abdullaev","DF","Dibba FC (UAE)"),
    ("Azizjon Ganiev","MF","Al Bataeh Club (UAE)"),
    ("Azizbek Amonov","FW","FK Dinamo Samarkand (UZB)"),
    ("Igor Sergeev","FW","Persepolis FC (IRN)"),
    ("Abbosbek Fayzullaev","MF","Başakşehir FK (TUR)"),
    ("Sherzod Esanov","MF","FK Buxoro (UZB)"),
    ("Behruzjon Karimov","DF","Surkhon FK (UZB)"),
    ("Avazbek Ulmasaliyev","DF","OKMK FK (UZB)"),
    ("Jakhongir Urozov","DF","FK Dinamo Samarkand (UZB)"),
]),

}  # end SQUADS


POS_GROUPS = {
    "TW": "Torwart",
    "IV": "Abwehr",
    "ZM": "Mittelfeld",
    "ST": "Angriff",
}

POS_ORDER = ["Torwart", "Abwehr", "Mittelfeld", "Angriff"]


def get_squad(flag_code: str) -> dict[str, list[dict]]:
    """Gibt den Kader gruppiert nach Positionsgruppe zurück."""
    players = SQUADS.get(flag_code, [])
    result: dict[str, list[dict]] = {g: [] for g in POS_ORDER}
    for p in players:
        group = POS_GROUPS.get(p["pos"], "Mittelfeld")
        result[group].append(p)
    return {k: v for k, v in result.items() if v}
